// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MOEGROUPEDMATMULATTRIBUTES_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_MOEGROUPEDMATMULATTRIBUTES_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace hipdnn_flatbuffers_sdk {
namespace data_objects {

struct MoeGroupedMatmulAttributes;
struct MoeGroupedMatmulAttributesBuilder;
struct MoeGroupedMatmulAttributesT;

bool operator==(const MoeGroupedMatmulAttributesT &lhs, const MoeGroupedMatmulAttributesT &rhs);
bool operator!=(const MoeGroupedMatmulAttributesT &lhs, const MoeGroupedMatmulAttributesT &rhs);

enum class MoeGroupedMatmulMode : int8_t {
  NONE = 0,
  GATHER = 1,
  SCATTER = 2,
  MIN = NONE,
  MAX = SCATTER
};

inline const MoeGroupedMatmulMode (&EnumValuesMoeGroupedMatmulMode())[3] {
  static const MoeGroupedMatmulMode values[] = {
    MoeGroupedMatmulMode::NONE,
    MoeGroupedMatmulMode::GATHER,
    MoeGroupedMatmulMode::SCATTER
  };
  return values;
}

inline const char * const *EnumNamesMoeGroupedMatmulMode() {
  static const char * const names[4] = {
    "NONE",
    "GATHER",
    "SCATTER",
    nullptr
  };
  return names;
}

inline const char *EnumNameMoeGroupedMatmulMode(MoeGroupedMatmulMode e) {
  if (::flatbuffers::IsOutRange(e, MoeGroupedMatmulMode::NONE, MoeGroupedMatmulMode::SCATTER)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMoeGroupedMatmulMode()[index];
}

struct MoeGroupedMatmulAttributesT : public ::flatbuffers::NativeTable {
  typedef MoeGroupedMatmulAttributes TableType;
  int64_t token_tensor_uid = 0;
  int64_t weight_tensor_uid = 0;
  int64_t first_token_offset_tensor_uid = 0;
  ::flatbuffers::Optional<int64_t> token_index_tensor_uid = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<int64_t> token_ks_tensor_uid = ::flatbuffers::nullopt;
  int64_t output_tensor_uid = 0;
  hipdnn_flatbuffers_sdk::data_objects::MoeGroupedMatmulMode mode = hipdnn_flatbuffers_sdk::data_objects::MoeGroupedMatmulMode::NONE;
  int32_t top_k = 0;
};

struct MoeGroupedMatmulAttributes FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MoeGroupedMatmulAttributesT NativeTableType;
  typedef MoeGroupedMatmulAttributesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TOKEN_TENSOR_UID = 4,
    VT_WEIGHT_TENSOR_UID = 6,
    VT_FIRST_TOKEN_OFFSET_TENSOR_UID = 8,
    VT_TOKEN_INDEX_TENSOR_UID = 10,
    VT_TOKEN_KS_TENSOR_UID = 12,
    VT_OUTPUT_TENSOR_UID = 14,
    VT_MODE = 16,
    VT_TOP_K = 18
  };
  int64_t token_tensor_uid() const {
    return GetField<int64_t>(VT_TOKEN_TENSOR_UID, 0);
  }
  bool mutate_token_tensor_uid(int64_t _token_tensor_uid = 0) {
    return SetField<int64_t>(VT_TOKEN_TENSOR_UID, _token_tensor_uid, 0);
  }
  int64_t weight_tensor_uid() const {
    return GetField<int64_t>(VT_WEIGHT_TENSOR_UID, 0);
  }
  bool mutate_weight_tensor_uid(int64_t _weight_tensor_uid = 0) {
    return SetField<int64_t>(VT_WEIGHT_TENSOR_UID, _weight_tensor_uid, 0);
  }
  int64_t first_token_offset_tensor_uid() const {
    return GetField<int64_t>(VT_FIRST_TOKEN_OFFSET_TENSOR_UID, 0);
  }
  bool mutate_first_token_offset_tensor_uid(int64_t _first_token_offset_tensor_uid = 0) {
    return SetField<int64_t>(VT_FIRST_TOKEN_OFFSET_TENSOR_UID, _first_token_offset_tensor_uid, 0);
  }
  ::flatbuffers::Optional<int64_t> token_index_tensor_uid() const {
    return GetOptional<int64_t, int64_t>(VT_TOKEN_INDEX_TENSOR_UID);
  }
  bool mutate_token_index_tensor_uid(int64_t _token_index_tensor_uid) {
    return SetField<int64_t>(VT_TOKEN_INDEX_TENSOR_UID, _token_index_tensor_uid);
  }
  ::flatbuffers::Optional<int64_t> token_ks_tensor_uid() const {
    return GetOptional<int64_t, int64_t>(VT_TOKEN_KS_TENSOR_UID);
  }
  bool mutate_token_ks_tensor_uid(int64_t _token_ks_tensor_uid) {
    return SetField<int64_t>(VT_TOKEN_KS_TENSOR_UID, _token_ks_tensor_uid);
  }
  int64_t output_tensor_uid() const {
    return GetField<int64_t>(VT_OUTPUT_TENSOR_UID, 0);
  }
  bool mutate_output_tensor_uid(int64_t _output_tensor_uid = 0) {
    return SetField<int64_t>(VT_OUTPUT_TENSOR_UID, _output_tensor_uid, 0);
  }
  hipdnn_flatbuffers_sdk::data_objects::MoeGroupedMatmulMode mode() const {
    return static_cast<hipdnn_flatbuffers_sdk::data_objects::MoeGroupedMatmulMode>(GetField<int8_t>(VT_MODE, 0));
  }
  bool mutate_mode(hipdnn_flatbuffers_sdk::data_objects::MoeGroupedMatmulMode _mode = static_cast<hipdnn_flatbuffers_sdk::data_objects::MoeGroupedMatmulMode>(0)) {
    return SetField<int8_t>(VT_MODE, static_cast<int8_t>(_mode), 0);
  }
  int32_t top_k() const {
    return GetField<int32_t>(VT_TOP_K, 0);
  }
  bool mutate_top_k(int32_t _top_k = 0) {
    return SetField<int32_t>(VT_TOP_K, _top_k, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_TOKEN_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_WEIGHT_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_FIRST_TOKEN_OFFSET_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_TOKEN_INDEX_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_TOKEN_KS_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_OUTPUT_TENSOR_UID, 8) &&
           VerifyField<int8_t>(verifier, VT_MODE, 1) &&
           VerifyField<int32_t>(verifier, VT_TOP_K, 4) &&
           verifier.EndTable();
  }
  MoeGroupedMatmulAttributesT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MoeGroupedMatmulAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<MoeGroupedMatmulAttributes> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MoeGroupedMatmulAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MoeGroupedMatmulAttributesBuilder {
  typedef MoeGroupedMatmulAttributes Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_token_tensor_uid(int64_t token_tensor_uid) {
    fbb_.AddElement<int64_t>(MoeGroupedMatmulAttributes::VT_TOKEN_TENSOR_UID, token_tensor_uid, 0);
  }
  void add_weight_tensor_uid(int64_t weight_tensor_uid) {
    fbb_.AddElement<int64_t>(MoeGroupedMatmulAttributes::VT_WEIGHT_TENSOR_UID, weight_tensor_uid, 0);
  }
  void add_first_token_offset_tensor_uid(int64_t first_token_offset_tensor_uid) {
    fbb_.AddElement<int64_t>(MoeGroupedMatmulAttributes::VT_FIRST_TOKEN_OFFSET_TENSOR_UID, first_token_offset_tensor_uid, 0);
  }
  void add_token_index_tensor_uid(int64_t token_index_tensor_uid) {
    fbb_.AddElement<int64_t>(MoeGroupedMatmulAttributes::VT_TOKEN_INDEX_TENSOR_UID, token_index_tensor_uid);
  }
  void add_token_ks_tensor_uid(int64_t token_ks_tensor_uid) {
    fbb_.AddElement<int64_t>(MoeGroupedMatmulAttributes::VT_TOKEN_KS_TENSOR_UID, token_ks_tensor_uid);
  }
  void add_output_tensor_uid(int64_t output_tensor_uid) {
    fbb_.AddElement<int64_t>(MoeGroupedMatmulAttributes::VT_OUTPUT_TENSOR_UID, output_tensor_uid, 0);
  }
  void add_mode(hipdnn_flatbuffers_sdk::data_objects::MoeGroupedMatmulMode mode) {
    fbb_.AddElement<int8_t>(MoeGroupedMatmulAttributes::VT_MODE, static_cast<int8_t>(mode), 0);
  }
  void add_top_k(int32_t top_k) {
    fbb_.AddElement<int32_t>(MoeGroupedMatmulAttributes::VT_TOP_K, top_k, 0);
  }
  explicit MoeGroupedMatmulAttributesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MoeGroupedMatmulAttributes> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MoeGroupedMatmulAttributes>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MoeGroupedMatmulAttributes> CreateMoeGroupedMatmulAttributes(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t token_tensor_uid = 0,
    int64_t weight_tensor_uid = 0,
    int64_t first_token_offset_tensor_uid = 0,
    ::flatbuffers::Optional<int64_t> token_index_tensor_uid = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<int64_t> token_ks_tensor_uid = ::flatbuffers::nullopt,
    int64_t output_tensor_uid = 0,
    hipdnn_flatbuffers_sdk::data_objects::MoeGroupedMatmulMode mode = hipdnn_flatbuffers_sdk::data_objects::MoeGroupedMatmulMode::NONE,
    int32_t top_k = 0) {
  MoeGroupedMatmulAttributesBuilder builder_(_fbb);
  builder_.add_output_tensor_uid(output_tensor_uid);
  if(token_ks_tensor_uid) { builder_.add_token_ks_tensor_uid(*token_ks_tensor_uid); }
  if(token_index_tensor_uid) { builder_.add_token_index_tensor_uid(*token_index_tensor_uid); }
  builder_.add_first_token_offset_tensor_uid(first_token_offset_tensor_uid);
  builder_.add_weight_tensor_uid(weight_tensor_uid);
  builder_.add_token_tensor_uid(token_tensor_uid);
  builder_.add_top_k(top_k);
  builder_.add_mode(mode);
  return builder_.Finish();
}

::flatbuffers::Offset<MoeGroupedMatmulAttributes> CreateMoeGroupedMatmulAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const MoeGroupedMatmulAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const MoeGroupedMatmulAttributesT &lhs, const MoeGroupedMatmulAttributesT &rhs) {
  return
      (lhs.token_tensor_uid == rhs.token_tensor_uid) &&
      (lhs.weight_tensor_uid == rhs.weight_tensor_uid) &&
      (lhs.first_token_offset_tensor_uid == rhs.first_token_offset_tensor_uid) &&
      (lhs.token_index_tensor_uid == rhs.token_index_tensor_uid) &&
      (lhs.token_ks_tensor_uid == rhs.token_ks_tensor_uid) &&
      (lhs.output_tensor_uid == rhs.output_tensor_uid) &&
      (lhs.mode == rhs.mode) &&
      (lhs.top_k == rhs.top_k);
}

inline bool operator!=(const MoeGroupedMatmulAttributesT &lhs, const MoeGroupedMatmulAttributesT &rhs) {
    return !(lhs == rhs);
}


inline MoeGroupedMatmulAttributesT *MoeGroupedMatmulAttributes::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<MoeGroupedMatmulAttributesT>(new MoeGroupedMatmulAttributesT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void MoeGroupedMatmulAttributes::UnPackTo(MoeGroupedMatmulAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = token_tensor_uid(); _o->token_tensor_uid = _e; }
  { auto _e = weight_tensor_uid(); _o->weight_tensor_uid = _e; }
  { auto _e = first_token_offset_tensor_uid(); _o->first_token_offset_tensor_uid = _e; }
  { auto _e = token_index_tensor_uid(); _o->token_index_tensor_uid = _e; }
  { auto _e = token_ks_tensor_uid(); _o->token_ks_tensor_uid = _e; }
  { auto _e = output_tensor_uid(); _o->output_tensor_uid = _e; }
  { auto _e = mode(); _o->mode = _e; }
  { auto _e = top_k(); _o->top_k = _e; }
}

inline ::flatbuffers::Offset<MoeGroupedMatmulAttributes> MoeGroupedMatmulAttributes::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MoeGroupedMatmulAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateMoeGroupedMatmulAttributes(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<MoeGroupedMatmulAttributes> CreateMoeGroupedMatmulAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const MoeGroupedMatmulAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const MoeGroupedMatmulAttributesT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _token_tensor_uid = _o->token_tensor_uid;
  auto _weight_tensor_uid = _o->weight_tensor_uid;
  auto _first_token_offset_tensor_uid = _o->first_token_offset_tensor_uid;
  auto _token_index_tensor_uid = _o->token_index_tensor_uid;
  auto _token_ks_tensor_uid = _o->token_ks_tensor_uid;
  auto _output_tensor_uid = _o->output_tensor_uid;
  auto _mode = _o->mode;
  auto _top_k = _o->top_k;
  return hipdnn_flatbuffers_sdk::data_objects::CreateMoeGroupedMatmulAttributes(
      _fbb,
      _token_tensor_uid,
      _weight_tensor_uid,
      _first_token_offset_tensor_uid,
      _token_index_tensor_uid,
      _token_ks_tensor_uid,
      _output_tensor_uid,
      _mode,
      _top_k);
}

}  // namespace data_objects
}  // namespace hipdnn_flatbuffers_sdk

#endif  // FLATBUFFERS_GENERATED_MOEGROUPEDMATMULATTRIBUTES_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
