// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MOEGROUPEDMATMULBWDATTRIBUTES_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_MOEGROUPEDMATMULBWDATTRIBUTES_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace hipdnn_flatbuffers_sdk {
namespace data_objects {

struct MoeGroupedMatmulBwdAttributes;
struct MoeGroupedMatmulBwdAttributesBuilder;
struct MoeGroupedMatmulBwdAttributesT;

bool operator==(const MoeGroupedMatmulBwdAttributesT &lhs, const MoeGroupedMatmulBwdAttributesT &rhs);
bool operator!=(const MoeGroupedMatmulBwdAttributesT &lhs, const MoeGroupedMatmulBwdAttributesT &rhs);

struct MoeGroupedMatmulBwdAttributesT : public ::flatbuffers::NativeTable {
  typedef MoeGroupedMatmulBwdAttributes TableType;
  int64_t doutput_tensor_uid = 0;
  int64_t token_tensor_uid = 0;
  int64_t first_token_offset_tensor_uid = 0;
  int64_t dweight_tensor_uid = 0;
};

struct MoeGroupedMatmulBwdAttributes FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MoeGroupedMatmulBwdAttributesT NativeTableType;
  typedef MoeGroupedMatmulBwdAttributesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DOUTPUT_TENSOR_UID = 4,
    VT_TOKEN_TENSOR_UID = 6,
    VT_FIRST_TOKEN_OFFSET_TENSOR_UID = 8,
    VT_DWEIGHT_TENSOR_UID = 10
  };
  int64_t doutput_tensor_uid() const {
    return GetField<int64_t>(VT_DOUTPUT_TENSOR_UID, 0);
  }
  bool mutate_doutput_tensor_uid(int64_t _doutput_tensor_uid = 0) {
    return SetField<int64_t>(VT_DOUTPUT_TENSOR_UID, _doutput_tensor_uid, 0);
  }
  int64_t token_tensor_uid() const {
    return GetField<int64_t>(VT_TOKEN_TENSOR_UID, 0);
  }
  bool mutate_token_tensor_uid(int64_t _token_tensor_uid = 0) {
    return SetField<int64_t>(VT_TOKEN_TENSOR_UID, _token_tensor_uid, 0);
  }
  int64_t first_token_offset_tensor_uid() const {
    return GetField<int64_t>(VT_FIRST_TOKEN_OFFSET_TENSOR_UID, 0);
  }
  bool mutate_first_token_offset_tensor_uid(int64_t _first_token_offset_tensor_uid = 0) {
    return SetField<int64_t>(VT_FIRST_TOKEN_OFFSET_TENSOR_UID, _first_token_offset_tensor_uid, 0);
  }
  int64_t dweight_tensor_uid() const {
    return GetField<int64_t>(VT_DWEIGHT_TENSOR_UID, 0);
  }
  bool mutate_dweight_tensor_uid(int64_t _dweight_tensor_uid = 0) {
    return SetField<int64_t>(VT_DWEIGHT_TENSOR_UID, _dweight_tensor_uid, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_DOUTPUT_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_TOKEN_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_FIRST_TOKEN_OFFSET_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_DWEIGHT_TENSOR_UID, 8) &&
           verifier.EndTable();
  }
  MoeGroupedMatmulBwdAttributesT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MoeGroupedMatmulBwdAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<MoeGroupedMatmulBwdAttributes> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MoeGroupedMatmulBwdAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MoeGroupedMatmulBwdAttributesBuilder {
  typedef MoeGroupedMatmulBwdAttributes Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_doutput_tensor_uid(int64_t doutput_tensor_uid) {
    fbb_.AddElement<int64_t>(MoeGroupedMatmulBwdAttributes::VT_DOUTPUT_TENSOR_UID, doutput_tensor_uid, 0);
  }
  void add_token_tensor_uid(int64_t token_tensor_uid) {
    fbb_.AddElement<int64_t>(MoeGroupedMatmulBwdAttributes::VT_TOKEN_TENSOR_UID, token_tensor_uid, 0);
  }
  void add_first_token_offset_tensor_uid(int64_t first_token_offset_tensor_uid) {
    fbb_.AddElement<int64_t>(MoeGroupedMatmulBwdAttributes::VT_FIRST_TOKEN_OFFSET_TENSOR_UID, first_token_offset_tensor_uid, 0);
  }
  void add_dweight_tensor_uid(int64_t dweight_tensor_uid) {
    fbb_.AddElement<int64_t>(MoeGroupedMatmulBwdAttributes::VT_DWEIGHT_TENSOR_UID, dweight_tensor_uid, 0);
  }
  explicit MoeGroupedMatmulBwdAttributesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MoeGroupedMatmulBwdAttributes> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MoeGroupedMatmulBwdAttributes>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MoeGroupedMatmulBwdAttributes> CreateMoeGroupedMatmulBwdAttributes(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t doutput_tensor_uid = 0,
    int64_t token_tensor_uid = 0,
    int64_t first_token_offset_tensor_uid = 0,
    int64_t dweight_tensor_uid = 0) {
  MoeGroupedMatmulBwdAttributesBuilder builder_(_fbb);
  builder_.add_dweight_tensor_uid(dweight_tensor_uid);
  builder_.add_first_token_offset_tensor_uid(first_token_offset_tensor_uid);
  builder_.add_token_tensor_uid(token_tensor_uid);
  builder_.add_doutput_tensor_uid(doutput_tensor_uid);
  return builder_.Finish();
}

::flatbuffers::Offset<MoeGroupedMatmulBwdAttributes> CreateMoeGroupedMatmulBwdAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const MoeGroupedMatmulBwdAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const MoeGroupedMatmulBwdAttributesT &lhs, const MoeGroupedMatmulBwdAttributesT &rhs) {
  return
      (lhs.doutput_tensor_uid == rhs.doutput_tensor_uid) &&
      (lhs.token_tensor_uid == rhs.token_tensor_uid) &&
      (lhs.first_token_offset_tensor_uid == rhs.first_token_offset_tensor_uid) &&
      (lhs.dweight_tensor_uid == rhs.dweight_tensor_uid);
}

inline bool operator!=(const MoeGroupedMatmulBwdAttributesT &lhs, const MoeGroupedMatmulBwdAttributesT &rhs) {
    return !(lhs == rhs);
}


inline MoeGroupedMatmulBwdAttributesT *MoeGroupedMatmulBwdAttributes::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<MoeGroupedMatmulBwdAttributesT>(new MoeGroupedMatmulBwdAttributesT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void MoeGroupedMatmulBwdAttributes::UnPackTo(MoeGroupedMatmulBwdAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = doutput_tensor_uid(); _o->doutput_tensor_uid = _e; }
  { auto _e = token_tensor_uid(); _o->token_tensor_uid = _e; }
  { auto _e = first_token_offset_tensor_uid(); _o->first_token_offset_tensor_uid = _e; }
  { auto _e = dweight_tensor_uid(); _o->dweight_tensor_uid = _e; }
}

inline ::flatbuffers::Offset<MoeGroupedMatmulBwdAttributes> MoeGroupedMatmulBwdAttributes::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MoeGroupedMatmulBwdAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateMoeGroupedMatmulBwdAttributes(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<MoeGroupedMatmulBwdAttributes> CreateMoeGroupedMatmulBwdAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const MoeGroupedMatmulBwdAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const MoeGroupedMatmulBwdAttributesT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _doutput_tensor_uid = _o->doutput_tensor_uid;
  auto _token_tensor_uid = _o->token_tensor_uid;
  auto _first_token_offset_tensor_uid = _o->first_token_offset_tensor_uid;
  auto _dweight_tensor_uid = _o->dweight_tensor_uid;
  return hipdnn_flatbuffers_sdk::data_objects::CreateMoeGroupedMatmulBwdAttributes(
      _fbb,
      _doutput_tensor_uid,
      _token_tensor_uid,
      _first_token_offset_tensor_uid,
      _dweight_tensor_uid);
}

}  // namespace data_objects
}  // namespace hipdnn_flatbuffers_sdk

#endif  // FLATBUFFERS_GENERATED_MOEGROUPEDMATMULBWDATTRIBUTES_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
