"""Mutation-kill tests for Tensile.CustomYamlLoader (slices 6/7/8 campaign).

Add-only characterization tests that pin observable behavior so that
mutmut survivors are killed. Generated by the kill-slices-6-7-8 workflow
and trampoline-verified per mutant.
"""
import builtins
from unittest import mock
import pytest
from Tensile.CustomYamlLoader import DEFAULT_YAML_LOADER, load_yaml_stream
from Tensile.CustomYamlLoader import DEFAULT_YAML_LOADER, load_yaml_dict_item
from Tensile.CustomYamlLoader import DEFAULT_YAML_LOADER, parse_scalar
from Tensile.CustomYamlLoader import DEFAULT_YAML_LOADER, load_yaml_sequence_item


# --- survivors of load_yaml_dict_item ---
class TestLoadYamlDictItemErrorMessage:
    """Pin the exact RuntimeError message raised when the YAML root is not a
    mapping. The message text is load-bearing for the several string-mutation
    survivors, so assert it verbatim rather than merely 'raises'."""

    def test_load_yaml_dict_item_sequence_root_exact_message(self, tmp_path):
        path = tmp_path / "logic.yaml"
        path.write_text("- a\n- b\n")
        with pytest.raises(RuntimeError) as excinfo:
            load_yaml_dict_item(path, DEFAULT_YAML_LOADER, "key")
        assert str(excinfo.value) == "Root of YAML is not a map"

    def test_load_yaml_dict_item_scalar_root_exact_message(self, tmp_path):
        # A bare scalar root is also not a MappingStartEvent -> same error.
        path = tmp_path / "logic.yaml"
        path.write_text("42\n")
        with pytest.raises(RuntimeError) as excinfo:
            load_yaml_dict_item(path, DEFAULT_YAML_LOADER, "key")
        assert str(excinfo.value) == "Root of YAML is not a map"


# --- survivors of load_yaml_sequence_item ---
def _write_yaml_lysi(tmp_path, text):
    p = tmp_path / "lysi.yaml"
    p.write_text(text)
    return p


class TestLoadYamlSequenceItemKills:
    def test_lysi_root_not_sequence_exact_message(self, tmp_path):
        p = _write_yaml_lysi(tmp_path, "key: value\n")
        with pytest.raises(RuntimeError) as excinfo:
            load_yaml_sequence_item(p, DEFAULT_YAML_LOADER, 0)
        assert str(excinfo.value) == "Root of YAML is not a sequence"

    def test_lysi_negative_index_terminates_and_returns_none(self, tmp_path):
        """A negative index is never matched; the original loop guard detects
        the SequenceEndEvent and returns None. A mutant whose guard no longer
        recognizes the sequence end never terminates for a negative index."""
        p = _write_yaml_lysi(tmp_path, "- a\n- b\n")
        assert load_yaml_sequence_item(p, DEFAULT_YAML_LOADER, -1) is None


# --- survivors of load_yaml_stream ---
class TestLoadYamlStreamOpenMode:
    def test_load_yaml_stream_opens_path_in_explicit_text_read_mode(self, tmp_path):
        # Kills the mutant that drops the explicit 'r' mode from open():
        # open(yaml_path, 'r') -> open(yaml_path). The parsed result is
        # identical because 'r' is the default, so distinguish via the open
        # call's positional arguments while still delegating to the real open
        # so the loader gets a working file object.
        p = tmp_path / "d.yaml"
        p.write_text("k: 1\nseq: [1, 2, three]\n")

        real_open = builtins.open
        recorded = []

        def spy(*args, **kwargs):
            recorded.append((args, kwargs))
            return real_open(*args, **kwargs)

        with mock.patch("builtins.open", side_effect=spy):
            result = load_yaml_stream(p, DEFAULT_YAML_LOADER)

        # Behavior is preserved (characterizes the real parse).
        assert result == {"k": 1, "seq": [1, 2, "three"]}

        # The first open() call must pass mode 'r' explicitly (original source);
        # the mutant omits it, leaving only the path positional arg.
        assert recorded, "open() was never called"
        args, kwargs = recorded[0]
        mode = args[1] if len(args) > 1 else kwargs.get("mode")
        assert mode == "r"


# --- survivors of parse_scalar ---
class TestParseScalarNumericBranch:
    @staticmethod
    def _parse_scalar(text):
        loader = DEFAULT_YAML_LOADER(text)
        loader.get_event()  # StreamStartEvent
        loader.get_event()  # DocumentStartEvent
        return parse_scalar(loader)

    @pytest.mark.parametrize(
        "text,expected",
        [
            ("5", 5),
            ("+5", 5),
            ("-3", -3),
            ("007", 7),
            ("0", 0),
            ("-0", 0),
        ],
    )
    def test_parse_scalar_integer_branch_values(self, text, expected):
        result = self._parse_scalar(text)
        assert result == expected
        assert type(result) is int

    @pytest.mark.parametrize(
        "text",
        ["x5", "5x", "abc", "5.0e"],
    )
    def test_parse_scalar_non_numeric_lstrip_falls_through_to_string(self, text):
        result = self._parse_scalar(text)
        assert result == text
        assert isinstance(result, str)

    @pytest.mark.parametrize("text", ["++5", "--5", "+-5"])
    def test_parse_scalar_multisign_raises_valueerror(self, text):
        """Pin the actual (latent-bug) behavior: value.lstrip('+-').isnumeric()
        accepts multi-sign strings, but the subsequent int(value_lower) rejects
        them and raises ValueError rather than falling through to string."""
        with pytest.raises(ValueError):
            self._parse_scalar(text)
