"""Mutation-kill tests for Tensile.SolutionStructs.Utilities (slices 6/7/8 campaign).

Add-only characterization tests that pin observable behavior so that
mutmut survivors are killed. Generated by the kill-slices-6-7-8 workflow
and trampoline-verified per mutant.
"""
import pytest
import Tensile.SolutionStructs.Utilities as U


# --- survivors of reject ---
class TestRejectSurvivors:
    def test_reject_default_print_reason_writes_header(self, capsys):
        # Default printSolutionRejectionReason omitted -> defaults to True, so the
        # "\nreject: " header is written to stdout. Kills default-arg flip to False.
        state = {"Valid": True}
        result = U.reject(state)
        captured = capsys.readouterr()
        assert result is True
        assert state["Valid"] is False
        assert captured.out == "\nreject: "

    def test_reject_header_exact_text(self, capsys):
        # The header string written is exactly "\nreject: " (lowercase, no XX markers).
        state = {"Valid": True}
        result = U.reject(state, True)
        captured = capsys.readouterr()
        assert result is True
        assert captured.out == "\nreject: "

    def test_reject_prints_each_arg_value(self, capsys):
        # Each *args value is printed verbatim (print(a)), not print(None).
        state = {"Valid": True}
        result = U.reject(state, True, "myreason")
        captured = capsys.readouterr()
        assert result is True
        assert captured.out == "\nreject: myreason\n"

    def test_reject_missing_solution_index_returns_true_no_raise(self, capsys):
        # state is not None but has no "SolutionIndex": the AND guard yields False,
        # solutionIndex defaults to exactly -1, so `solutionIndex != -1` is False and
        # no Exception is raised. Kills: AND->OR (KeyError), -1->+1 (raise), -1->-2 (raise).
        state = {"Valid": True, "ProblemType": "PT_placeholder"}
        result = U.reject(state, True)
        captured = capsys.readouterr()
        assert result is True
        assert state["Valid"] is False
        assert captured.out == "\nreject: "
