"""Mutation-kill tests for Tensile.SolutionStructs.LdsPadding (slices 6/7/8 campaign).

Add-only characterization tests that pin observable behavior so that
mutmut survivors are killed. Generated by the kill-slices-6-7-8 workflow
and trampoline-verified per mutant.
"""
import pytest
import Tensile.SolutionStructs.LdsPadding as L
from Tensile.SolutionStructs.LdsPadding import _b64_check


# --- survivors of b128_base_addrs_fp16 ---
class TestB128BaseAddrsFp16Survivors:
    @pytest.mark.parametrize("mt,expected", [
        (3, [0, 6, 12, 18, 24, 30, 36, 42, 16, 22, 28, 34, 40, 46, 52, 58]),
        (1, [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]),
    ])
    def test_b128_base_addrs_fp16_exact_output(self, mt, expected):
        result = L._b128_base_addrs_fp16(mt)
        assert result == expected
        assert len(result) == 16
        assert all(isinstance(a, int) for a in result)


# --- survivors of b128_check ---
class Test_b128_check_survivors:
    """White-box kills for `_b128_check` mutation survivors (slice 6b).

    `_b128_check(half, B, P, wOffsets, instOffs)` returns True iff, for every
    (wOff, instOff) combination, the padded per-thread b128 addresses are all
    16-byte aligned and every thread's 4 consecutive banks are collectively
    distinct (16 threads * 4 banks == 64 distinct banks). All expected values
    were verified against the unmutated source.
    """

    # A canonical conflict-free layout: 16 threads at 16*k give quad bases
    # 4k (k=0..15), covering all 64 banks with no conflict -> True.
    CF16 = [16 * k for k in range(16)]

    @pytest.mark.parametrize(
        "half,B,P,wOffsets,instOffs,expected",
        [
            # base True case: kills %->/ , %16->%17, ==0->==1, >>2 sign/shift,
            # range(4)->range(5), bk=None, in->not in, return True->False
            (CF16, 0, 0, (0,), (0,), True),
            # a>>2 >= 64 forces the %64 wrap that (a>>2)/64 (mutmut_19) drops:
            # thread bases collide under % but not under / -> orig False.
            ([0, 1024], 0, 0, (0,), (0,), False),
            # empty instOffs: original falls back to (0,) (aligned -> True);
            # mutmut_5 falls back to (1,) which misaligns every address.
            (CF16, 0, 0, (0,), (), True),
            # instOff=256 pushes a>>2 into the wrap range so base%64 vs base%65
            # (mutmut_22) diverge, while the layout stays conflict-free -> True.
            (CF16, 0, 0, (0,), (256,), True),
            # addresses all == 4 (mod 16); instOff=12 aligns them (a+io True),
            # mutmut_8 computes a-io == 8 (mod 16) -> misaligned -> False.
            ([4, 68, 132, 196], 0, 0, (0,), (12,), True),
            # same asymmetry via wOff: a+wOff aligned; mutmut_9 uses a-wOff.
            ([4, 68, 132, 196], 0, 0, (12,), (0,), True),
            # B=16,P=16 pad shifts addresses to distinct quads (True); the
            # mutmut_1 minus-sign pad collapses both to 0 -> bank conflict.
            ([192, 208], 16, 16, (0,), (0,), True),
        ],
        ids=[
            "cf16_true", "wrap_conflict_false", "empty_instoffs_true",
            "instoff256_true", "instoff_align_asym", "woff_align_asym",
            "pad_sign_true",
        ],
    )
    def test_b128_check_behavior(self, half, B, P, wOffsets, instOffs, expected):
        assert L._b128_check(half, B, P, wOffsets, instOffs) is expected

    def test_b128_check_range5_extra_bank_conflicts(self):
        # Guards mutmut_24 (range(4)->range(5)): the conflict-free CF16 layout
        # tiles all 64 banks exactly; a 5th bank per thread must collide.
        assert L._b128_check(self.CF16, 0, 0, (0,), (0,)) is True

    def test_b128_check_return_true_not_false(self):
        # Guards mutmut_32 (final `return True`->`return False`): a fully
        # conflict-free, aligned layout must return True.
        assert L._b128_check(self.CF16, 0, 0, (0,), (0,)) is True


# --- survivors of b32_check ---
class TestB32CheckKills:
    _B32_CASES = [
        ([i * 4 for i in range(32)], 0, 4, (0,), (0,), True),
        ([i * 4 for i in range(31)], 0, 4, (0,), (0,), False),
        ([i * 4 for i in range(32)], 16, 4, (0,), (0,), True),
        ([0, 12, 16, 20, 72, 80, 84, 88, 112, 120, 124, 144, 168, 172, 192,
          200, 244, 280, 292, 316, 320, 324, 344, 348, 356, 396, 400, 432,
          448, 464, 480, 484, 488], 16, 2, (52,), (4,), False),
        ([0, 4, 16, 32, 36, 44, 60, 64, 80, 104, 108, 124, 128, 140, 148,
          160, 164, 168, 176, 224, 240, 244, 256, 304, 316, 332, 348, 380,
          392, 396, 432, 464, 472], 16, 8, (8,), (4,), False),
        ([4, 84, 124, 160, 172, 176, 180, 184, 212, 220, 228, 236, 272, 276,
          288, 304, 320, 348, 356, 360, 372, 392, 396, 412, 420, 424, 428,
          448, 452, 484, 496, 500, 508], 128, 1, (32,), (), True),
        ([8, 16, 44, 56, 68, 76, 84, 96, 112, 124, 128, 156, 172, 184, 188,
          212, 216, 240, 244, 260, 264, 268, 288, 348, 352, 364, 380, 384,
          392, 400, 416, 444, 472], 128, 4, (36,), (0, 4), True),
        ([8, 52, 76, 80, 88, 100, 112, 136, 140, 148, 168, 172, 184, 204,
          248, 260, 284, 288, 300, 324, 328, 348, 356, 364, 392, 396, 404,
          416, 444, 456, 472, 484, 500], 32, 2, (0, 4), (0,), False),
    ]

    @pytest.mark.parametrize("rawAddrs,B,P,wOffsets,instOffs,expected", _B32_CASES)
    def test_b32_check_exact(self, rawAddrs, B, P, wOffsets, instOffs, expected):
        assert L._b32_check(rawAddrs, B, P, wOffsets, instOffs) is expected

    def test_b32_check_default_instoffs_is_zero_tuple(self):
        rawAddrs = [i * 4 for i in range(32)]
        assert L._b32_check(rawAddrs, 0, 4, (0,)) is True


# --- survivors of b32_search_padding ---
class TestB32SearchPaddingKill:
    """Exact-behavior characterization of ``_b32_search_padding`` on hand-picked
    inputs that pin every observable branch of the (B, P) search: the largest-B /
    lowest-overhead pick, the descending-order tie-break, the argmin-by-overhead
    selection, the ``mtBytes = mt*4`` validB filter, the ``padDw`` scan bounds, the
    per-instruction-offset ``_b32_check`` constraint, and the exact return dict keys
    / values. All expected values were derived from the real source logic.
    """

    # banks (raw//4)%64 collide at io=0 -> needs pad; lowest overhead is B=256,P=16dw
    _RAW0 = [(t % 16 + t // 16 * 64) * 4 for t in range(32)]
    # already conflict-free (banks 0..31): smallest pad at largest B
    _CF = [4 * t for t in range(32)]
    # two configs share the minimum overhead 0.15625 (256/10dw == 128/5dw): tie
    _TIE = [204, 100, 268, 668, 588, 480, 384, 296, 436, 92, 224, 416, 572, 284,
            492, 288, 716, 544, 516, 248, 388, 16, 508, 744, 400, 380, 780, 556,
            728, 108, 460, 228]
    # argmin-by-overhead picks B=64,P=21dw; a P*B objective would pick B=8
    _SEL = [496, 708, 476, 232, 96, 776, 908, 772, 72, 664, 52, 24, 940, 512, 432,
            360, 952, 208, 816, 1148, 112, 540, 212, 280, 116, 20, 524, 864, 1072,
            1188, 580, 136]
    # with instOffs={0,16} no config passes (None); ignoring instOffs -> 32/60dw
    _KRAW = [2772, 3076, 3792, 3832, 1192, 288, 3880, 3452, 436, 2916, 308, 552,
             1168, 1796, 3252, 3364, 3688, 1912, 1376, 28, 828, 60, 872, 3104,
             3700, 1672, 620, 1412, 3200, 3288, 1588, 1044]
    # mt=48 -> mtBytes=192 keeps validB nonempty; mt/4=12.0 empties it (None)
    _R48 = [1040, 1024, 48, 748, 912, 192, 880, 316, 560, 232, 764, 516, 432, 672,
            288, 1140, 456, 12, 468, 988, 732, 260, 836, 700, 872, 900, 228, 512,
            108, 1080, 604, 1052]
    # wOffsets=(0,512) matters: dropping it -> B=1024 instead of 512
    _WM = [568, 1164, 388, 1548, 1388, 1424, 688, 796, 1200, 256, 44, 100, 208,
           508, 840, 1344, 240, 776, 632, 280, 560, 408, 828, 64, 1376, 860, 844,
           696, 144, 428, 924, 292]

    _CASES = [
        ("baseline",  64,  _RAW0, (0,),    (0,),    {"perBlock": 256,  "pad": 16}),
        ("conflict_free", 16, _CF, (0,),   (0,),    {"perBlock": 1024, "pad": 1}),
        ("overhead_tie", 128, _TIE, (0,),  (0,),    {"perBlock": 256,  "pad": 10}),
        ("argmin_overhead", 32, _SEL, (0,), (0,),   {"perBlock": 64,   "pad": 21}),
        ("instoff_no_config", 256, _KRAW, (0,), (0, 16), None),
        ("instoff_zero", 256, _KRAW, (0,), (0,),    {"perBlock": 32,   "pad": 60}),
        ("mtbytes_filter", 48, _R48, (0,), (0,),    {"perBlock": 32,   "pad": 22}),
        ("multi_woffset", 64, _WM, (0, 512), (0,),  {"perBlock": 512,  "pad": 5}),
    ]

    @pytest.mark.parametrize(
        "cid,mt,raw,woff,ioff,expected", _CASES, ids=[c[0] for c in _CASES]
    )
    def test_b32_search_padding_exact(self, cid, mt, raw, woff, ioff, expected):
        assert L._b32_search_padding(mt, list(raw), woff, ioff) == expected


# --- survivors of b64_base_addrs_fp4 ---
class TestB64BaseAddrsFp4Kill:
    """Kill mutants in _b64_base_addrs_fp4 by pinning the exact per-lane
    base-address tuples for FP4. The natural per-thread index is
    t = (w//16)*8 + ((w%16)//8)*32 + w%8, and each address is
    int(t * mt * 0.5). Return is (addrs[:16], addrs[16:])."""

    def test_b64_base_addrs_fp4_exact_mt8(self):
        half0, half1 = L._b64_base_addrs_fp4(8)
        assert half0 == [0, 4, 8, 12, 16, 20, 24, 28,
                         128, 132, 136, 140, 144, 148, 152, 156]
        assert half1 == [32, 36, 40, 44, 48, 52, 56, 60,
                         160, 164, 168, 172, 176, 180, 184, 188]

    def test_b64_base_addrs_fp4_exact_mt64(self):
        half0, half1 = L._b64_base_addrs_fp4(64)
        assert half0 == [0, 32, 64, 96, 128, 160, 192, 224,
                         1024, 1056, 1088, 1120, 1152, 1184, 1216, 1248]
        assert half1 == [256, 288, 320, 352, 384, 416, 448, 480,
                         1280, 1312, 1344, 1376, 1408, 1440, 1472, 1504]

    def test_b64_base_addrs_fp4_halves_length_16(self):
        half0, half1 = L._b64_base_addrs_fp4(8)
        assert len(half0) == 16
        assert len(half1) == 16
        assert all(isinstance(a, int) for a in half0 + half1)


# --- survivors of b64_base_addrs_fp8 ---
class TestB64BaseAddrsFp8:
    """Pin the exact FP8 per-lane base-address tables produced by
    ``_b64_base_addrs_fp8``. half0[i] = tH[i] + kH0[i]*mt and
    half1[i] = tH[i] + kH1[i]*mt with
      kH0 = (0,1,2,3,0,1,2,3,4,5,6,7,4,5,6,7)
      kH1 = (16,17,18,19,16,17,18,19,20,21,22,23,20,21,22,23)
      tH  = (0,0,0,0,8,8,8,8,0,0,0,0,8,8,8,8).
    Exact equality kills every per-element table mutant, the None-tuple
    subscript mutants, the +/-, */ operator mutants (mt=128 makes the
    division non-integral), and the range(None)/range(17) mutants.
    """

    def test_b64_base_addrs_fp8_mt128_exact(self):
        expected0 = [0, 128, 256, 384, 8, 136, 264, 392,
                     512, 640, 768, 896, 520, 648, 776, 904]
        expected1 = [2048, 2176, 2304, 2432, 2056, 2184, 2312, 2440,
                     2560, 2688, 2816, 2944, 2568, 2696, 2824, 2952]
        result = L._b64_base_addrs_fp8(128)
        assert result == (expected0, expected1)

    def test_b64_base_addrs_fp8_mt64_exact(self):
        expected0 = [0, 64, 128, 192, 8, 72, 136, 200,
                     256, 320, 384, 448, 264, 328, 392, 456]
        expected1 = [1024, 1088, 1152, 1216, 1032, 1096, 1160, 1224,
                     1280, 1344, 1408, 1472, 1288, 1352, 1416, 1480]
        result = L._b64_base_addrs_fp8(64)
        assert result == (expected0, expected1)

    def test_b64_base_addrs_fp8_shape_and_type(self):
        half0, half1 = L._b64_base_addrs_fp8(128)
        assert isinstance(half0, list) and isinstance(half1, list)
        assert len(half0) == 16 and len(half1) == 16
        assert all(isinstance(v, int) for v in half0 + half1)

    def test_b64_base_addrs_fp8_division_nonintegral(self):
        half0, half1 = L._b64_base_addrs_fp8(128)
        assert half0[1] == 128 and not isinstance(half0[1], float)
        assert half1[0] == 2048 and not isinstance(half1[0], float)
        assert half0[1] != 128 / 128
        assert half1[0] != 16 / 128


# --- survivors of b64_check ---
pytestmark = pytest.mark.unit


_B64_CHECK_CASES = [
    ("full_pass", [0, 8, 16, 24], [32, 40, 48, 56], 64, 4, (0,), (0,), 0, {}, True),
    ("half_pass", [0, 8, 16, 24], [4, 12, 20, 28], 64, 4, (0,), (0,), 0, {}, True),
    ("misaligned", [2, 10, 18, 26], [34, 42, 50, 58], 64, 4, (0,), (0,), 0, {}, False),
    ("full_conflict", [0, 8, 16, 24], [0, 8, 16, 24], 64, 4, (0,), (0,), 0, {}, False),
    ("half_conflict_h0", [0, 0, 16, 24], [4, 12, 20, 28], 64, 4, (0,), (0,), 0, {}, False),
    ("half_conflict_h1", [0, 8, 16, 24], [4, 4, 20, 28], 64, 4, (0,), (0,), 0, {}, False),
    ("pure_on_half", [0, 8, 16, 24], [4, 12, 20, 28], 64, 4, (0,), (0,), 0,
     {"require_pure_full_wave": True}, False),
    ("pure_on_full", [0, 8, 16, 24], [32, 40, 48, 56], 64, 4, (0,), (0,), 0,
     {"require_pure_full_wave": True}, True),
    ("some_on_half", [0, 8, 16, 24], [4, 12, 20, 28], 64, 4, (0,), (0,), 0,
     {"require_some_full_wave": True}, False),
    ("some_on_full", [0, 8, 16, 24], [32, 40, 48, 56], 64, 4, (0,), (0,), 0,
     {"require_some_full_wave": True}, True),
    ("wOff_pass", [0, 8, 16, 24], [32, 40, 48, 56], 64, 4, (0,), (8,), 0, {}, True),
    ("shift_pass", [0, 8, 16, 24], [32, 40, 48, 56], 64, 4, (0,), (0,), 8, {}, True),
    ("instOff_pass", [0, 8, 16, 24], [32, 40, 48, 56], 64, 4, (8,), (0,), 0, {}, True),
    ("padB", [0, 8, 16, 24], [64, 72, 80, 88], 64, 4, (0,), (0,), 0, {}, True),
    ("wrap_mod64", [0, 512], [16, 528], 1024, 0, (0,), (0,), 0, {}, False),
    ("mod65_a", [252, 256], [8], 1024, 0, (0,), (0,), 0, {}, False),
    ("secondbank_wrap", [0, 4], [16], 1024, 0, (0,), (0,), 0, {}, False),
    ("mod65_b", [252, 0], [16], 1024, 0, (0,), (0,), 0, {}, False),
    ("wOff_h0_sign", [40], [120, 200, 488, 272], 256, 32, (0,), (32, 64), 8, {}, False),
    ("instOff_sign", [220, 56], [48, 36, 152], 1024, 8, (3,), (4,), 1, {}, True),
    ("delta_h0_sign", [248], [248, 152, 8], 16, 8, (8, 64), (4,), 4, {}, False),
]


class TestB64CheckKills:
    @pytest.mark.parametrize(
        "half0,half1,B,P,instOffs,wOffsets,shift,kwargs,expected",
        [c[1:] for c in _B64_CHECK_CASES],
        ids=[c[0] for c in _B64_CHECK_CASES],
    )
    def test_b64_check_exact(self, half0, half1, B, P, instOffs,
                             wOffsets, shift, kwargs, expected):
        assert _b64_check(half0, half1, B, P, instOffs, wOffsets,
                          shift, **kwargs) is expected


# --- survivors of b64_compute_config ---
class TestB64ComputeConfigMutants:
    # White-box: call the internal solver directly with realistic (instOffs, wOffsets)
    # built from the module's own emit helpers, and pin the exact (perBlock, pad,
    # shift) result. matrixInstM is fixed at 16 (the public defaults), so the
    # per-wave M shift in bytes is int(16 * bpeDS): 8 for FP4, 16 for FP8.

    # (label, mt, bpeDS, addrFn_name, minB, lrvw, ipt, wt, wg, expected)
    _CASES = [
        ("A_fp4_mt64",  64,  0.5, "_b64_base_addrs_fp4",  8, 32, 64, 2, 2,
         {"perBlock": 1024, "pad": 8,   "shift": 4}),
        ("B_fp4_mt384", 384, 0.5, "_b64_base_addrs_fp4",  8, 32, 64, 2, 2,
         {"perBlock": 64,   "pad": 12,  "shift": 4}),
        ("C_fp8_mt96",  96,  1.0, "_b64_base_addrs_fp8", 16, 16, 64, 1, 1,
         {"perBlock": 16,   "pad": 4,   "shift": 4}),
        ("D_fp4_mt96",  96,  0.5, "_b64_base_addrs_fp4",  8, 32, 64, 2, 2,
         {"perBlock": 16,   "pad": 4,   "shift": 4}),
        ("E_fp4_mt384", 384, 0.5, "_b64_base_addrs_fp4",  8, 32, 64, 1, 1,
         {"perBlock": 64,   "pad": 12,  "shift": 4}),
        ("F_fp4_mt32",  32,  0.5, "_b64_base_addrs_fp4",  8, 32, 64, 1, 1,
         {"perBlock": 512,  "pad": 8,   "shift": 0}),
        ("G_fp4_mt16",  16,  0.5, "_b64_base_addrs_fp4",  8, 16, 32, 2, 2,
         {"perBlock": 256,  "pad": 128, "shift": 0}),
    ]

    @pytest.mark.parametrize(
        "label,mt,bpeDS,addrFnName,minB,lrvw,ipt,wt,wg,expected",
        _CASES,
        ids=[c[0] for c in _CASES],
    )
    def test_b64_compute_config_exact(self, label, mt, bpeDS, addrFnName,
                                      minB, lrvw, ipt, wt, wg, expected):
        addrFn = getattr(L, addrFnName)
        instOffs = L._b64_emit_instOffs(mt, bpeDS, lrvw, ipt, wt)
        wOffsets = L._b64_w_offsets(wg, int(16 * bpeDS))
        cfg = L._b64_compute_config(mt, bpeDS, addrFn, minB, instOffs, wOffsets)
        assert cfg == expected

    def test_b64_compute_config_empty_validB_all_zero(self):
        # minB larger than every valid block size -> no candidate B -> no config
        # in any tier -> exact all-zero dict with the canonical keys.
        cfg = L._b64_compute_config(128, 0.5, L._b64_base_addrs_fp4, 2048, (0,), (0,))
        assert cfg == {"perBlock": 0, "pad": 0, "shift": 0}

    def test_b64_compute_config_empty_instoffs_selects_tier1_shift0(self):
        """With no instructions to emit, tier-1 (pure-full-wave at shift=0)
        passes vacuously and must be selected, so shift stays 0. This pins the
        tier-1 policy tuple as (shift=0, pure=True, some_full=False); flipping
        some_full to True rejects the vacuous pass and falls through to tier-3
        (shift=4)."""
        cfg = L._b64_compute_config(64, 1.0, L._b64_base_addrs_fp8, 16, (), (0,))
        assert cfg == {"perBlock": 1024, "pad": 4, "shift": 0}


# --- survivors of b64_emit_instOffs ---
class TestB64EmitInstOffsKill:
    @pytest.mark.parametrize(
        "mt,bpeDS,lrvw,miInputPerThread,miWaveTile,expected",
        [
            (128, 0.5, 32, 64, 2, (0, 32, 1024, 1056, 4096, 4128, 5120, 5152)),
            (128, 1.0, 16, 64, 2, (0, 64, 1024, 1088, 4096, 4160, 5120, 5184,
                                   8192, 8256, 9216, 9280, 12288, 12352, 13312, 13376)),
            (64, 0.5, 1, 2, 1, (0, 2048)),
            (64, 0.5, 8, 2, 1, (0,)),
            (64, 0.5, 16, 2, 1, (0,)),
            (128, 1.0, 1, 2, 3, (0, 42, 84, 4096, 4138, 4180)),
            (64, 0.5, 1, 2, 2, (0, 16, 2048, 2064)),
            (64, 0.5, 32, 2, 1, (0, 512)),
        ],
    )
    def test_b64_emit_instOffs_exact(self, mt, bpeDS, lrvw, miInputPerThread,
                                     miWaveTile, expected):
        assert L._b64_emit_instOffs(mt, bpeDS, lrvw, miInputPerThread,
                                    miWaveTile) == expected


# --- survivors of b64_w_offsets ---
class TestB64WOffsetsKills:
    @pytest.mark.parametrize("miWaveGroup, matrixInstMBytes, expected", [
        (0, 8, (0,)),
        (1, 8, (0,)),
        (2, 8, (0, 8)),
        (3, 8, (0, 8, 16)),
        (4, 5, (0, 5, 10, 15)),
    ])
    def test_b64_w_offsets_exact_table(self, miWaveGroup, matrixInstMBytes, expected):
        result = L._b64_w_offsets(miWaveGroup, matrixInstMBytes)
        assert result == expected
        assert all(isinstance(x, int) for x in result)

    def test_b64_w_offsets_multiplies_not_divides(self):
        # w * m at w=1: original 8, mutant (w / m) -> 0.125
        assert L._b64_w_offsets(2, 8) == (0, 8)
        assert L._b64_w_offsets(2, 8)[1] == 8

    def test_b64_w_offsets_floor_is_one_not_two(self):
        # max(miWaveGroup, 1): for miWaveGroup <= 1 length must be 1, not 2
        assert L._b64_w_offsets(1, 8) == (0,)
        assert len(L._b64_w_offsets(1, 8)) == 1
        assert L._b64_w_offsets(0, 8) == (0,)
        assert len(L._b64_w_offsets(0, 8)) == 1


# --- survivors of build_fp16_instOffs ---
class TestBuildFp16InstOffsChar:
    # Base case: mt=64, miInputPerThUnroll=8, lrvw=2, miWaveTile=3,
    # miWaveGroup=2, vw=4, matrixInstM omitted (default 16).
    #   numberLRVWPerMIInput = 8 // 2 = 4
    #   incrementBytes       = 4 * 2 * 64 * 2 = 1024
    #   miWaveGroupShape     = 16 * 2 * 4 = 128
    #   value(tIdx,kRead)    = kRead + tIdx * 128 * 2 = kRead + tIdx*256
    #   tIdx in range(max(3,1))=0,1,2 ; kRead in (0, 1024)
    #   set -> sorted = (0, 256, 512, 1024, 1280, 1536)  (all int)

    def test_build_fp16_instOffs_base_exact_value(self):
        result = L._build_fp16_instOffs(64, 8, 2, 3, 2, 4)
        assert result == (0, 256, 512, 1024, 1280, 1536)

    def test_build_fp16_instOffs_base_all_int(self):
        # Any float-introducing (`/` for `*`, or `* 3`, etc.) mutant either
        # changes a value or leaves float elements that compare == to the int
        # tuple; assert exact int type to pin integral arithmetic.
        result = L._build_fp16_instOffs(64, 8, 2, 3, 2, 4)
        assert result == (0, 256, 512, 1024, 1280, 1536)
        assert all(type(x) is int for x in result)
        assert len(result) == 6

    def test_build_fp16_instOffs_default_matrixInstM_is_16(self):
        # matrixInstM omitted -> default must be 16 (miWaveGroupShape=128).
        # If default were 17, miWaveGroupShape=136 -> value stride 272.
        omitted = L._build_fp16_instOffs(64, 8, 2, 3, 2, 4)
        explicit16 = L._build_fp16_instOffs(64, 8, 2, 3, 2, 4, 16)
        assert omitted == explicit16 == (0, 256, 512, 1024, 1280, 1536)
        assert omitted != L._build_fp16_instOffs(64, 8, 2, 3, 2, 4, 17)

    def test_build_fp16_instOffs_wavetile_one_floor(self):
        # miWaveTile=1 -> range(max(1,1))=range(1): single tIdx=0.
        #   -> {0, incrementBytes=1024} -> (0, 1024).
        # Distinguishes max(miWaveTile,2) (would yield range(2) -> extra
        # (256,1280)) and max(1)/max(miWaveTile,)/max(None,...) (raise).
        assert L._build_fp16_instOffs(64, 8, 2, 1, 2, 4) == (0, 1024)

    def test_build_fp16_instOffs_kread_starts_at_zero(self):
        # 0 must be present as the low kRead offset (tuple begins with 0).
        assert L._build_fp16_instOffs(64, 8, 2, 1, 2, 4)[0] == 0


# --- survivors of build_fp32_instOffs ---
class TestBuildFp32InstOffsKills:
    # Four hand-computed cases pin _build_fp32_instOffs exactly.
    # (mt, vw, lrvw, miInputPerThread, miWaveTile, miWaveGroup, xf32EmuPack) -> expected tuple.
    # matrixInstM is deliberately OMITTED so the default (16) path is exercised
    # (kills the matrixInstM=16->17 default-arg mutant).
    _FP32_INSTOFFS_CASES = [
        # Case A: xf32=False, nRPU=4, numVectorsPerTile=4, numReadsPerVector=2, miWaveGroup=2
        (
            dict(mt=32, vw=2, lrvw=2, miInputPerThread=8, miWaveTile=8,
                 miWaveGroup=2, xf32EmuPack=False),
            (0, 4, 256, 260, 512, 516, 768, 772, 1024, 1028, 1280, 1284, 1536, 1540),
        ),
        # Case B: xf32=True (exercises the emu-pack kFn branch)
        (
            dict(mt=32, vw=2, lrvw=2, miInputPerThread=8, miWaveTile=8,
                 miWaveGroup=2, xf32EmuPack=True),
            (0, 4, 256, 260, 512, 516, 768, 772, 1024, 1028, 1280, 1284,
             1536, 1540, 1792, 1796),
        ),
        # Case C: miWaveTile//vw == 1 so numVectorsPerTile clamps to 1 (kills max(...,2))
        (
            dict(mt=32, vw=2, lrvw=2, miInputPerThread=8, miWaveTile=2,
                 miWaveGroup=1, xf32EmuPack=False),
            (0, 4, 256, 260, 512, 516, 768, 772),
        ),
        # Case D: vw==1 so numReadsPerVector clamps to 1 (kills max(vw,2))
        (
            dict(mt=32, vw=1, lrvw=2, miInputPerThread=8, miWaveTile=8,
                 miWaveGroup=2, xf32EmuPack=False),
            (0, 128, 256, 384, 512, 640, 768, 896, 1024, 1152, 1280, 1408, 1536, 1664),
        ),
    ]

    @pytest.mark.parametrize(
        "kwargs,expected",
        _FP32_INSTOFFS_CASES,
        ids=["A_base", "B_xf32", "C_clampV", "D_clampE"],
    )
    def test_build_fp32_instOffs_exact(self, kwargs, expected):
        assert L._build_fp32_instOffs(**kwargs) == expected


# --- survivors of get_fp32_mt_config ---
class TestGetFp32MtConfigXf32EmuPack:
    """Pin get_fp32_mt_config for FP32/XF32 ds_load_b32.

    All three surviving mutants only alter the xf32EmuPack value that is
    forwarded into _compute_fp32_config (default False->True; value->None;
    argument omitted->callee default False). These tests characterize the
    real outputs and, in test_..._invariant_to_xf32EmuPack, pin the observed
    fact that xf32EmuPack has no effect on the returned config: the emulation
    pack changes the ds_load_b32 instruction offsets fed to the bank-conflict
    solver, but the minimal (perBlock, pad) it selects is identical for
    True/False/None/omitted across the whole realistic input domain. This is
    why the three mutants are observationally equivalent through this public
    selector (see dispositions).
    """

    # (mt, vw, lrvw, wg, mipt, wt) -> (perBlock, pad), values derived from
    # the current unmutated _compute_fp32_config logic.
    _CASES = [
        (64, 4, 1, 2, 4, 4, 256, 1),
        (128, 2, 1, 1, 4, 2, 512, 1),
        (256, 4, 2, 2, 8, 4, 1024, 1),
        (96, 2, 1, 1, 4, 2, 0, 0),
        (512, 4, 4, 2, 8, 4, 0, 0),
    ]

    @pytest.mark.parametrize(
        "mt,vw,lrvw,wg,mipt,wt,exp_perBlock,exp_pad",
        _CASES,
        ids=[f"mt{c[0]}_vw{c[1]}_lrvw{c[2]}_wg{c[3]}_ipt{c[4]}_wt{c[5]}"
             for c in _CASES],
    )
    def test_get_fp32_mt_config_values(self, mt, vw, lrvw, wg, mipt, wt,
                                       exp_perBlock, exp_pad):
        assert L.get_fp32_mt_config(mt, "perBlock", vw, lrvw, wg, mipt, wt) == exp_perBlock
        assert L.get_fp32_mt_config(mt, "pad", vw, lrvw, wg, mipt, wt) == exp_pad

    @pytest.mark.parametrize(
        "mt,vw,lrvw,wg,mipt,wt,exp_perBlock,exp_pad",
        _CASES,
        ids=[f"mt{c[0]}_vw{c[1]}_lrvw{c[2]}_wg{c[3]}_ipt{c[4]}_wt{c[5]}"
             for c in _CASES],
    )
    def test_get_fp32_mt_config_invariant_to_xf32EmuPack(
        self, mt, vw, lrvw, wg, mipt, wt, exp_perBlock, exp_pad
    ):
        for key, expected in (("perBlock", exp_perBlock), ("pad", exp_pad)):
            omitted = L.get_fp32_mt_config(mt, key, vw, lrvw, wg, mipt, wt)
            false_ = L.get_fp32_mt_config(mt, key, vw, lrvw, wg, mipt, wt, xf32EmuPack=False)
            true_ = L.get_fp32_mt_config(mt, key, vw, lrvw, wg, mipt, wt, xf32EmuPack=True)
            none_ = L.get_fp32_mt_config(mt, key, vw, lrvw, wg, mipt, wt, xf32EmuPack=None)
            assert omitted == expected
            assert false_ == expected
            assert true_ == expected
            assert none_ == expected
