# Copyright Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

"""Decode names produced by :mod:`Tensile.SolutionStructs.Naming`.

The encoder intentionally optimizes names for file and symbol length.  This
module provides the inverse operation for diagnostics and developer tooling.
It derives parameter abbreviations and encoded values from the same in-tree
registries as the encoder, avoiding a second hand-maintained naming table.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import cache
import re
from typing import Any

from Tensile.Common.RequiredParameters import (
    getRequiredParametersFull,
    getRequiredParametersMin,
)
from Tensile.Common.ValidParameters import newMIValidParameters, validParameters
from Tensile.SolutionStructs.Naming import (
    getParameterNameAbbreviation,
    getParameterValueAbbreviation,
)


_STRUCTURAL_PATTERN = re.compile(
    r"^(?P<tag>MT|MI)(?P<dims>\d+(?:x\d+){2,8})$"
)
_SHORTENED_NAME_PATTERN = re.compile(r"[A-Za-z0-9_-]{43}=$")
_INTEGER_PATTERN = re.compile(r"^-?\d+$")
_NEGATIVE_INTEGER_PATTERN = re.compile(r"^n(\d+)$")
_FLOAT_PATTERN = re.compile(r"^(\d+)p(\d{2})$")
_VALUE_CONTINUATION_PATTERN = re.compile(r"^(?:n?\d+|\d+p\d{2}|M)$")

# Names found in shipped logic generated by earlier naming schemas, plus
# derived fields that have appeared in names without being registered in
# ValidParameters. Current names still come from ValidParameters and Naming.
_COMPATIBILITY_PARAMETER_ALIASES = {
    "1LDSBuffer": ("1LDSB",),
    "AssertFree0ElementMultiple": ("AF0EM",),
    "AssertFree1ElementMultiple": ("AF1EM",),
    "GlobalReadVectorWidth": ("GRVW",),
    "VectorAtomicWidth": ("VAW",),
}
_COMPATIBILITY_PARAMETER_VALUES = {
    "ClusterBarrier": [False, True],
    "FractionalLoad": [0, 1],
    "LdsBlockSizePerPad": None,
    "LocalSplitU": None,
    "UnrollMajorLDSA": [False, True],
    "UnrollMajorLDSB": [False, True],
    "VectorWidth": None,
}
_MASKABLE_PARAMETERS = {
    "GlobalSplitU",
    "GlobalSplitUCoalesced",
    "GlobalSplitUWorkGroupMappingRoundRobin",
    "SFCWGM",
    "StaggerU",
    "StaggerUMapping",
    "StaggerUStride",
    "WorkGroupMapping",
    "WorkGroupMappingXCCGroup",
}

__all__ = [
    "DecodedKernelName",
    "DecodedParameter",
    "KernelNameDecodeError",
    "decode_kernel_name",
]


class KernelNameDecodeError(ValueError):
    """Raised when an input cannot be interpreted as a kernel name."""


@dataclass(frozen=True)
class DecodedParameter:
    """One encoded component from a kernel or solution name."""

    component: str
    name: str | None
    abbreviation: str | None
    encoded_value: str | None
    value: Any
    status: str
    candidates: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        result = {
            "component": self.component,
            "name": self.name,
            "abbreviation": self.abbreviation,
            "encoded_value": self.encoded_value,
            "value": _json_value(self.value),
            "status": self.status,
        }
        if self.candidates:
            result["candidates"] = list(self.candidates)
        return result


@dataclass(frozen=True)
class DecodedKernelName:
    """Structured result returned by :func:`decode_kernel_name`."""

    kernel_name: str
    problem_type: str
    parameters: tuple[DecodedParameter, ...]
    complete: bool
    truncated: bool
    warnings: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        return {
            "kernel_name": self.kernel_name,
            "problem_type": self.problem_type,
            "complete": self.complete,
            "truncated": self.truncated,
            "parameters": [parameter.to_dict() for parameter in self.parameters],
            "warnings": list(self.warnings),
        }


@dataclass(frozen=True)
class _ParameterSpec:
    name: str
    abbreviation: str
    rank: int
    values: dict[str, Any]
    max_value_tokens: int
    open_values: bool


def _json_value(value: Any) -> Any:
    if value is None or isinstance(value, (bool, int, float, str)):
        return value
    if isinstance(value, dict):
        return {str(key): _json_value(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_value(item) for item in value]
    if hasattr(value, "major") and hasattr(value, "minor") and hasattr(value, "patch"):
        return [value.major, value.minor, value.patch]
    return str(value)


def _parameter_specs() -> tuple[_ParameterSpec, ...]:
    # MIWaveTile is added by Naming._getName for matrix-instruction kernels but
    # intentionally lives in newMIValidParameters rather than validParameters.
    names = (
        set(getRequiredParametersFull())
        | set(getRequiredParametersMin())
        | set(_COMPATIBILITY_PARAMETER_ALIASES)
        | set(_COMPATIBILITY_PARAMETER_VALUES)
    )
    names.add("MIWaveTile")
    names.discard("CustomKernelName")
    names.discard("MacroTile")
    names.discard("MatrixInstruction")

    specs = []
    for rank, name in enumerate(sorted(names)):
        abbreviations = (
            getParameterNameAbbreviation(name),
            *_COMPATIBILITY_PARAMETER_ALIASES.get(name, ()),
        )
        registry_value = validParameters.get(name, newMIValidParameters.get(name))
        if name in _COMPATIBILITY_PARAMETER_VALUES:
            registry_value = _COMPATIBILITY_PARAMETER_VALUES[name]
        if name in {"DirectToLdsA", "DirectToLdsB", "Kernel"}:
            registry_value = [False, True]
        values: dict[str, Any] = {}
        if isinstance(registry_value, list):
            for value in registry_value:
                encoded = getParameterValueAbbreviation(name, value)
                values.setdefault(encoded, _json_value(value))
        # Naming masks runtime-only values with M while identifying equivalent
        # kernels in getKeyNoInternalArgs.
        if name in _MASKABLE_PARAMETERS:
            values.setdefault("M", "M")
        open_values = not isinstance(registry_value, list)
        if open_values:
            values.setdefault("", "")
        max_value_tokens = max((value.count("_") + 1 for value in values), default=1)
        for abbreviation in dict.fromkeys(abbreviations):
            specs.append(
                _ParameterSpec(
                    name,
                    abbreviation,
                    rank,
                    values,
                    max_value_tokens,
                    open_values,
                )
            )
    return tuple(specs)


@cache
def _specs_by_initial() -> dict[str, tuple[_ParameterSpec, ...]]:
    by_initial: dict[str, list[_ParameterSpec]] = {}
    for spec in _parameter_specs():
        by_initial.setdefault(spec.abbreviation[0], []).append(spec)
    return {
        initial: tuple(
            sorted(specs, key=lambda item: len(item.abbreviation), reverse=True)
        )
        for initial, specs in by_initial.items()
    }


def _decode_inferred_value(name: str, encoded: str) -> Any:
    if encoded == "M":
        return "M"
    if name == "ISA" and len(encoded) >= 3:
        try:
            return [int(encoded[:-2]), int(encoded[-2]), int(encoded[-1], 16)]
        except ValueError:
            pass
    if "_" in encoded:
        return [_decode_inferred_value(name, part) for part in encoded.split("_")]
    negative_match = _NEGATIVE_INTEGER_PATTERN.fullmatch(encoded)
    if negative_match:
        return -int(negative_match.group(1))
    if _INTEGER_PATTERN.fullmatch(encoded):
        return int(encoded)
    float_match = _FLOAT_PATTERN.fullmatch(encoded)
    if float_match:
        return int(float_match.group(1)) + int(float_match.group(2)) / 100
    return encoded


def _known_value_match(
    spec: _ParameterSpec, tokens: list[str], index: int
) -> tuple[int, str, Any] | None:
    first = tokens[index]
    first_value = first[len(spec.abbreviation):]
    if not first_value:
        if "" in spec.values:
            return index + 1, "", spec.values[""]
        return None
    max_end = min(len(tokens), index + spec.max_value_tokens)
    for end in range(max_end, index, -1):
        encoded = "_".join([first_value, *tokens[index + 1:end]])
        if encoded in spec.values:
            return end, encoded, spec.values[encoded]
    return None


def _inferred_value_match(
    spec: _ParameterSpec, tokens: list[str], index: int
) -> tuple[int, str, Any] | None:
    first_value = tokens[index][len(spec.abbreviation):]
    if not first_value:
        if spec.values.get("0") is False and spec.values.get("1") is True:
            return index + 1, "", True
        return None
    end = index + 1
    # Underscores inside list/dict values are indistinguishable from component
    # separators. Naming currently emits numeric continuation tokens, so stop
    # before a letter-led component even when it is from a future version.
    while end < len(tokens) and _VALUE_CONTINUATION_PATTERN.fullmatch(tokens[end]):
        end += 1
    encoded = "_".join([first_value, *tokens[index + 1:end]])
    return end, encoded, _decode_inferred_value(spec.name, encoded)


def _matching_specs(token: str, minimum_rank: int) -> list[_ParameterSpec]:
    if not token or token[0] not in _specs_by_initial():
        return []
    return [
        spec
        for spec in _specs_by_initial()[token[0]]
        if spec.rank > minimum_rank and token.startswith(spec.abbreviation)
    ]


def _decode_suffix(tokens: list[str]) -> tuple[list[DecodedParameter], list[str]]:
    decoded: list[DecodedParameter] = []
    warnings: list[str] = []
    index = 0
    minimum_rank = -1

    while index < len(tokens):
        token = tokens[index]
        specs = _matching_specs(token, minimum_rank)
        order_violation = False
        if not specs:
            specs = _matching_specs(token, -1)
            order_violation = bool(specs)
        matches = []
        for spec in specs:
            known = _known_value_match(spec, tokens, index)
            if known:
                end, encoded, value = known
                matches.append((2, end, len(spec.abbreviation), spec, encoded, value))
                continue
            inferred = _inferred_value_match(spec, tokens, index)
            if inferred:
                end, encoded, value = inferred
                matches.append((1, end, len(spec.abbreviation), spec, encoded, value))

        if not matches:
            decoded.append(
                DecodedParameter(token, None, None, None, None, "unknown")
            )
            warnings.append(f"Unknown component: {token}")
            index += 1
            continue

        matches.sort(key=lambda item: (item[0], item[1], item[2]), reverse=True)
        best_score = matches[0][:3]
        best_matches = [match for match in matches if match[:3] == best_score]

        # AssertFree0ElementMultiple and AssertFree1ElementMultiple share AFEM.
        # Canonical names emit sorted parameters, so a following AFEM resolves
        # the first occurrence.  A lone occurrence is inherently ambiguous.
        if len(best_matches) > 1:
            same_component = all(
                match[1] == best_matches[0][1] and match[4] == best_matches[0][4]
                for match in best_matches
            )
            if same_component:
                end = best_matches[0][1]
                encoded = best_matches[0][4]
                value = best_matches[0][5]
                candidates = tuple(match[3].name for match in best_matches)
                has_later_collision = end < len(tokens) and any(
                    tokens[end].startswith(match[3].abbreviation)
                    for match in best_matches
                )
                if has_later_collision:
                    chosen = min(best_matches, key=lambda match: match[3].rank)
                else:
                    component = "_".join(tokens[index:end])
                    decoded.append(
                        DecodedParameter(
                            component,
                            None,
                            best_matches[0][3].abbreviation,
                            encoded,
                            value,
                            "ambiguous",
                            candidates,
                        )
                    )
                    warnings.append(
                        f"Ambiguous component {component}: {', '.join(candidates)}"
                    )
                    index = end
                    minimum_rank = max(match[3].rank for match in best_matches)
                    continue
            else:
                chosen = best_matches[0]
        else:
            chosen = best_matches[0]

        confidence, end, _, spec, encoded, value = chosen
        component = "_".join(tokens[index:end])
        status = "decoded" if confidence == 2 or spec.open_values else "inferred"
        decoded.append(
            DecodedParameter(
                component,
                spec.name,
                spec.abbreviation,
                encoded,
                value,
                status,
            )
        )
        if status == "inferred":
            warnings.append(
                f"Value {encoded!r} for {spec.name} is not in the current "
                "valid-parameter registry"
            )
        if order_violation:
            warnings.append(
                f"Component {component} is outside canonical parameter order"
            )
        index = end
        minimum_rank = spec.rank

    return decoded, warnings


def _structural_parameter(token: str) -> DecodedParameter:
    match = _STRUCTURAL_PATTERN.fullmatch(token)
    if not match:
        raise KernelNameDecodeError(f"Invalid structural component: {token}")
    name = "MacroTile" if match.group("tag") == "MT" else "MatrixInstruction"
    value = [int(part) for part in match.group("dims").split("x")]
    return DecodedParameter(
        token,
        name,
        match.group("tag"),
        match.group("dims"),
        value,
        "decoded",
    )


def decode_kernel_name(kernel_name: str) -> DecodedKernelName:
    """Decode a canonical Tensile kernel or solution name.

    Unknown and historical components are retained in the result and mark it
    incomplete.  Structurally invalid input raises :class:`KernelNameDecodeError`.
    """

    if not isinstance(kernel_name, str):
        raise TypeError("kernel_name must be a string")
    kernel_name = kernel_name.strip()
    if not kernel_name:
        raise KernelNameDecodeError("kernel name must not be empty")
    if any(character.isspace() for character in kernel_name):
        raise KernelNameDecodeError("kernel name must not contain whitespace")

    tokens = kernel_name.split("_")
    truncated = bool(_SHORTENED_NAME_PATTERN.search(kernel_name))
    warnings = []
    if truncated:
        warnings.append(
            "Name contains an irreversible SHA-256 shortening suffix; "
            "parameters after the cut point cannot be decoded"
        )

    try:
        solution_marker = tokens.index("SN")
    except ValueError:
        solution_marker = -1

    prefix_end = solution_marker if solution_marker >= 0 else len(tokens)
    structural_start = next(
        (
            index
            for index, token in enumerate(tokens[:prefix_end])
            if _STRUCTURAL_PATTERN.fullmatch(token) or token == "CMS"
        ),
        prefix_end,
    )
    problem_type = "_".join(tokens[:structural_start])
    parameters: list[DecodedParameter] = []

    cursor = structural_start
    while cursor < prefix_end:
        token = tokens[cursor]
        if _STRUCTURAL_PATTERN.fullmatch(token):
            parameters.append(_structural_parameter(token))
        elif token == "CMS":
            parameters.append(
                DecodedParameter(
                    token,
                    "UseCustomMainLoopSchedule",
                    "CMS",
                    "1",
                    True,
                    "decoded",
                )
            )
        else:
            parameters.append(
                DecodedParameter(token, None, None, None, None, "unknown")
            )
            warnings.append(f"Unknown structural component: {token}")
        cursor += 1

    if solution_marker >= 0:
        suffix, suffix_warnings = _decode_suffix(tokens[solution_marker + 1:])
        parameters.extend(suffix)
        warnings.extend(suffix_warnings)
    else:
        warnings.append(
            "Solution-name marker SN was not found; only the problem type and "
            "structural fields could be decoded"
        )

    complete = not truncated and solution_marker >= 0 and all(
        parameter.status in {"decoded", "inferred"} for parameter in parameters
    )
    return DecodedKernelName(
        kernel_name,
        problem_type,
        tuple(parameters),
        complete,
        truncated,
        tuple(dict.fromkeys(warnings)),
    )
