// AUTOMATICALLY GENERATED by umd_registry_gen -- do not modify.
// Source: FlatBuffers reflection schema (graph.bfbs). See RFC 0018 Appendix B.
#pragma once

#include <cstddef>
#include <cstdint>
#include <string_view>

#include <hipdnn_flatbuffers_sdk/umd/OpSchemaRegistry.hpp>
#include <hipdnn_flatbuffers_sdk/data_objects/graph_generated.h>

namespace hipdnn_flatbuffers_sdk::umd
{
namespace generated
{

namespace op0 {
inline const AttrBinding attributes[] = {
    {"bias_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormInferenceAttributes*>(a)->bias_tensor_uid()); return s; }},
    {"inv_variance_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormInferenceAttributes*>(a)->inv_variance_tensor_uid()); return s; }},
    {"mean_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormInferenceAttributes*>(a)->mean_tensor_uid()); return s; }},
    {"scale_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormInferenceAttributes*>(a)->scale_tensor_uid()); return s; }},
    {"x_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormInferenceAttributes*>(a)->x_tensor_uid()); return s; }},
    {"y_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormInferenceAttributes*>(a)->y_tensor_uid()); return s; }},
};
} // namespace op0

namespace op1 {
inline const AttrBinding attributes[] = {
    {"axis_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::PointwiseAttributes*>(a)->axis_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"elu_alpha", true, AttrType::Float, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Float; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::PointwiseAttributes*>(a)->elu_alpha(); s.present = v.has_value(); if(v) s.f = static_cast<double>(*v); return s; }},
    {"in_0_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::PointwiseAttributes*>(a)->in_0_tensor_uid()); return s; }},
    {"in_1_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::PointwiseAttributes*>(a)->in_1_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"in_2_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::PointwiseAttributes*>(a)->in_2_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"operation", false, AttrType::Dtype, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Dtype; s.present = true; s.dtype = ::hipdnn_flatbuffers_sdk::data_objects::EnumNamePointwiseMode(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::PointwiseAttributes*>(a)->operation()); return s; }},
    {"out_0_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::PointwiseAttributes*>(a)->out_0_tensor_uid()); return s; }},
    {"relu_lower_clip", true, AttrType::Float, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Float; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::PointwiseAttributes*>(a)->relu_lower_clip(); s.present = v.has_value(); if(v) s.f = static_cast<double>(*v); return s; }},
    {"relu_lower_clip_slope", true, AttrType::Float, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Float; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::PointwiseAttributes*>(a)->relu_lower_clip_slope(); s.present = v.has_value(); if(v) s.f = static_cast<double>(*v); return s; }},
    {"relu_upper_clip", true, AttrType::Float, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Float; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::PointwiseAttributes*>(a)->relu_upper_clip(); s.present = v.has_value(); if(v) s.f = static_cast<double>(*v); return s; }},
    {"softplus_beta", true, AttrType::Float, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Float; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::PointwiseAttributes*>(a)->softplus_beta(); s.present = v.has_value(); if(v) s.f = static_cast<double>(*v); return s; }},
    {"swish_beta", true, AttrType::Float, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Float; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::PointwiseAttributes*>(a)->swish_beta(); s.present = v.has_value(); if(v) s.f = static_cast<double>(*v); return s; }},
};
} // namespace op1

namespace op2 {
inline const AttrBinding attributes[] = {
    {"dbias_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormBackwardAttributes*>(a)->dbias_tensor_uid()); return s; }},
    {"dscale_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormBackwardAttributes*>(a)->dscale_tensor_uid()); return s; }},
    {"dx_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormBackwardAttributes*>(a)->dx_tensor_uid()); return s; }},
    {"dy_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormBackwardAttributes*>(a)->dy_tensor_uid()); return s; }},
    {"inv_variance_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormBackwardAttributes*>(a)->inv_variance_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"mean_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormBackwardAttributes*>(a)->mean_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"scale_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormBackwardAttributes*>(a)->scale_tensor_uid()); return s; }},
    {"x_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormBackwardAttributes*>(a)->x_tensor_uid()); return s; }},
};
} // namespace op2

namespace op3 {
inline const AttrBinding attributes[] = {
    {"bias_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormAttributes*>(a)->bias_tensor_uid()); return s; }},
    {"epsilon_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormAttributes*>(a)->epsilon_tensor_uid()); return s; }},
    {"inv_variance_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormAttributes*>(a)->inv_variance_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"mean_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormAttributes*>(a)->mean_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"momentum_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormAttributes*>(a)->momentum_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"next_running_mean_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormAttributes*>(a)->next_running_mean_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"next_running_variance_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormAttributes*>(a)->next_running_variance_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"prev_running_mean_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormAttributes*>(a)->prev_running_mean_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"prev_running_variance_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormAttributes*>(a)->prev_running_variance_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"scale_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormAttributes*>(a)->scale_tensor_uid()); return s; }},
    {"x_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormAttributes*>(a)->x_tensor_uid()); return s; }},
    {"y_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormAttributes*>(a)->y_tensor_uid()); return s; }},
};
} // namespace op3

namespace op4 {
inline const AttrBinding attributes[] = {
    {"conv_mode", false, AttrType::Dtype, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Dtype; s.present = true; s.dtype = ::hipdnn_flatbuffers_sdk::data_objects::EnumNameConvMode(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ConvolutionFwdAttributes*>(a)->conv_mode()); return s; }},
    {"w_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ConvolutionFwdAttributes*>(a)->w_tensor_uid()); return s; }},
    {"x_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ConvolutionFwdAttributes*>(a)->x_tensor_uid()); return s; }},
    {"y_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ConvolutionFwdAttributes*>(a)->y_tensor_uid()); return s; }},
};
} // namespace op4

namespace op5 {
inline const AttrBinding attributes[] = {
    {"conv_mode", false, AttrType::Dtype, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Dtype; s.present = true; s.dtype = ::hipdnn_flatbuffers_sdk::data_objects::EnumNameConvMode(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ConvolutionBwdAttributes*>(a)->conv_mode()); return s; }},
    {"dx_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ConvolutionBwdAttributes*>(a)->dx_tensor_uid()); return s; }},
    {"dy_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ConvolutionBwdAttributes*>(a)->dy_tensor_uid()); return s; }},
    {"w_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ConvolutionBwdAttributes*>(a)->w_tensor_uid()); return s; }},
};
} // namespace op5

namespace op6 {
inline const AttrBinding attributes[] = {
    {"conv_mode", false, AttrType::Dtype, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Dtype; s.present = true; s.dtype = ::hipdnn_flatbuffers_sdk::data_objects::EnumNameConvMode(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ConvolutionWrwAttributes*>(a)->conv_mode()); return s; }},
    {"dw_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ConvolutionWrwAttributes*>(a)->dw_tensor_uid()); return s; }},
    {"dy_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ConvolutionWrwAttributes*>(a)->dy_tensor_uid()); return s; }},
    {"x_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ConvolutionWrwAttributes*>(a)->x_tensor_uid()); return s; }},
};
} // namespace op6

namespace op7 {
inline const AttrBinding attributes[] = {
    {"bias_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormInferenceAttributesVarianceExt*>(a)->bias_tensor_uid()); return s; }},
    {"epsilon_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormInferenceAttributesVarianceExt*>(a)->epsilon_tensor_uid()); return s; }},
    {"mean_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormInferenceAttributesVarianceExt*>(a)->mean_tensor_uid()); return s; }},
    {"scale_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormInferenceAttributesVarianceExt*>(a)->scale_tensor_uid()); return s; }},
    {"variance_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormInferenceAttributesVarianceExt*>(a)->variance_tensor_uid()); return s; }},
    {"x_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormInferenceAttributesVarianceExt*>(a)->x_tensor_uid()); return s; }},
    {"y_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BatchnormInferenceAttributesVarianceExt*>(a)->y_tensor_uid()); return s; }},
};
} // namespace op7

namespace op8 {
inline const AttrBinding attributes[] = {
    {"a_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::MatmulAttributes*>(a)->a_tensor_uid()); return s; }},
    {"b_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::MatmulAttributes*>(a)->b_tensor_uid()); return s; }},
    {"c_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::MatmulAttributes*>(a)->c_tensor_uid()); return s; }},
};
} // namespace op8

namespace op9 {
inline const AttrBinding attributes[] = {
    {"bias_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::RMSNormAttributes*>(a)->bias_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"epsilon_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::RMSNormAttributes*>(a)->epsilon_tensor_uid()); return s; }},
    {"forward_phase", false, AttrType::Dtype, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Dtype; s.present = true; s.dtype = ::hipdnn_flatbuffers_sdk::data_objects::EnumNameNormFwdPhase(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::RMSNormAttributes*>(a)->forward_phase()); return s; }},
    {"inv_rms_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::RMSNormAttributes*>(a)->inv_rms_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"scale_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::RMSNormAttributes*>(a)->scale_tensor_uid()); return s; }},
    {"x_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::RMSNormAttributes*>(a)->x_tensor_uid()); return s; }},
    {"y_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::RMSNormAttributes*>(a)->y_tensor_uid()); return s; }},
};
} // namespace op9

namespace op10 {
inline const AttrBinding attributes[] = {
    {"bias_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormAttributes*>(a)->bias_tensor_uid()); return s; }},
    {"epsilon_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormAttributes*>(a)->epsilon_tensor_uid()); return s; }},
    {"forward_phase", false, AttrType::Dtype, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Dtype; s.present = true; s.dtype = ::hipdnn_flatbuffers_sdk::data_objects::EnumNameNormFwdPhase(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormAttributes*>(a)->forward_phase()); return s; }},
    {"inv_variance_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormAttributes*>(a)->inv_variance_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"mean_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormAttributes*>(a)->mean_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"normalized_dim_count", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormAttributes*>(a)->normalized_dim_count()); return s; }},
    {"scale_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormAttributes*>(a)->scale_tensor_uid()); return s; }},
    {"x_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormAttributes*>(a)->x_tensor_uid()); return s; }},
    {"y_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormAttributes*>(a)->y_tensor_uid()); return s; }},
};
} // namespace op10

namespace op11 {
inline const OperandBinding operands[] = {
    {"attn_mask", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->attn_mask_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"block_mask", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->block_mask_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"descale_k", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->descale_k_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"descale_q", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->descale_q_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"descale_s", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->descale_s_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"descale_v", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->descale_v_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"dropout_mask", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->dropout_mask_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"dropout_scale", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->dropout_scale_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"K", false, +[](const void* a, std::int64_t& out) -> bool { out = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->k_tensor_uid(); return true; }},
    {"offset", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->offset_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"page_table_k", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->page_table_k_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"page_table_v", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->page_table_v_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"Q", false, +[](const void* a, std::int64_t& out) -> bool { out = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->q_tensor_uid(); return true; }},
    {"scale_o", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->scale_o_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"scale_s", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->scale_s_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"scale", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->scale_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"seed", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->seed_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"seq_len_kv", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->seq_len_kv_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"seq_len_q", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->seq_len_q_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"sink_token", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->sink_token_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"V", false, +[](const void* a, std::int64_t& out) -> bool { out = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->v_tensor_uid(); return true; }},
};
inline const ResultBinding results[] = {
    {"amax_o", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->amax_o_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"amax_s", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->amax_s_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"max", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->max_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"O", false, +[](const void* a, std::int64_t& out) -> bool { out = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->o_tensor_uid(); return true; }},
    {"rng_dump", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->rng_dump_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"stats", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->stats_tensor_uid(); if(!v) return false; out = *v; return true; }},
    {"sum_exp", true, +[](const void* a, std::int64_t& out) -> bool { auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->sum_exp_tensor_uid(); if(!v) return false; out = *v; return true; }},
};
inline const AttrBinding attributes[] = {
    {"alibi_mask", false, AttrType::Bool, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Bool; s.present = true; s.b = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->alibi_mask(); return s; }},
    {"attn_scale_value", true, AttrType::Float, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Float; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->attn_scale_value(); s.present = v.has_value(); if(v) s.f = static_cast<double>(*v); return s; }},
    {"causal_mask", false, AttrType::Bool, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Bool; s.present = true; s.b = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->causal_mask(); return s; }},
    {"causal_mask_bottom_right", false, AttrType::Bool, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Bool; s.present = true; s.b = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->causal_mask_bottom_right(); return s; }},
    {"diagonal_alignment", false, AttrType::Dtype, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Dtype; s.present = true; s.dtype = ::hipdnn_flatbuffers_sdk::data_objects::EnumNameDiagonalAlignment(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->diagonal_alignment()); return s; }},
    {"dropout_probability", true, AttrType::Float, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Float; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->dropout_probability(); s.present = v.has_value(); if(v) s.f = static_cast<double>(*v); return s; }},
    {"generate_stats", true, AttrType::Bool, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Bool; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->generate_stats(); s.present = v.has_value(); if(v) s.b = *v; return s; }},
    {"implementation", false, AttrType::Dtype, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Dtype; s.present = true; s.dtype = ::hipdnn_flatbuffers_sdk::data_objects::EnumNameAttentionImplementation(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->implementation()); return s; }},
    {"left_bound", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->left_bound(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"max_seq_len_kv", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->max_seq_len_kv(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"mma_core_mode", false, AttrType::Dtype, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Dtype; s.present = true; s.dtype = ::hipdnn_flatbuffers_sdk::data_objects::EnumNameDataType(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->mma_core_mode()); return s; }},
    {"padding_mask", false, AttrType::Bool, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Bool; s.present = true; s.b = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->padding_mask(); return s; }},
    {"right_bound", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaAttributes*>(a)->right_bound(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
};
} // namespace op11

namespace op12 {
inline const AttrBinding attributes[] = {
    {"is_negative_scale", false, AttrType::Bool, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Bool; s.present = true; s.b = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BlockScaleDequantizeAttributes*>(a)->is_negative_scale(); return s; }},
    {"scale_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BlockScaleDequantizeAttributes*>(a)->scale_tensor_uid()); return s; }},
    {"x_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BlockScaleDequantizeAttributes*>(a)->x_tensor_uid()); return s; }},
    {"y_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BlockScaleDequantizeAttributes*>(a)->y_tensor_uid()); return s; }},
};
} // namespace op12

namespace op13 {
inline const AttrBinding attributes[] = {
    {"axis", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BlockScaleQuantizeAttributes*>(a)->axis(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"block_size", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BlockScaleQuantizeAttributes*>(a)->block_size()); return s; }},
    {"scale_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BlockScaleQuantizeAttributes*>(a)->scale_tensor_uid()); return s; }},
    {"transpose", false, AttrType::Bool, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Bool; s.present = true; s.b = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BlockScaleQuantizeAttributes*>(a)->transpose(); return s; }},
    {"x_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BlockScaleQuantizeAttributes*>(a)->x_tensor_uid()); return s; }},
    {"y_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::BlockScaleQuantizeAttributes*>(a)->y_tensor_uid()); return s; }},
};
} // namespace op13

namespace op14 {
inline const AttrBinding attributes[] = {
    {"alibi_mask", false, AttrType::Bool, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Bool; s.present = true; s.b = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->alibi_mask(); return s; }},
    {"attn_mask_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->attn_mask_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"attn_scale_value", true, AttrType::Float, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Float; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->attn_scale_value(); s.present = v.has_value(); if(v) s.f = static_cast<double>(*v); return s; }},
    {"causal_mask", false, AttrType::Bool, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Bool; s.present = true; s.b = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->causal_mask(); return s; }},
    {"causal_mask_bottom_right", false, AttrType::Bool, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Bool; s.present = true; s.b = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->causal_mask_bottom_right(); return s; }},
    {"dbias_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->dbias_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"diagonal_alignment", false, AttrType::Dtype, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Dtype; s.present = true; s.dtype = ::hipdnn_flatbuffers_sdk::data_objects::EnumNameDiagonalAlignment(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->diagonal_alignment()); return s; }},
    {"dk_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->dk_tensor_uid()); return s; }},
    {"do_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->do_tensor_uid()); return s; }},
    {"dq_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->dq_tensor_uid()); return s; }},
    {"dropout_mask_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->dropout_mask_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"dropout_probability", true, AttrType::Float, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Float; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->dropout_probability(); s.present = v.has_value(); if(v) s.f = static_cast<double>(*v); return s; }},
    {"dropout_scale_inv_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->dropout_scale_inv_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"dropout_scale_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->dropout_scale_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"dv_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->dv_tensor_uid()); return s; }},
    {"k_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->k_tensor_uid()); return s; }},
    {"left_bound", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->left_bound(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"o_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->o_tensor_uid()); return s; }},
    {"offset_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->offset_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"padding_mask", false, AttrType::Bool, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Bool; s.present = true; s.b = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->padding_mask(); return s; }},
    {"q_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->q_tensor_uid()); return s; }},
    {"right_bound", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->right_bound(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"scale_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->scale_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"seed_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->seed_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"seq_len_kv_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->seq_len_kv_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"seq_len_q_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->seq_len_q_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"stats_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->stats_tensor_uid()); return s; }},
    {"v_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::SdpaBackwardAttributes*>(a)->v_tensor_uid()); return s; }},
};
} // namespace op14

namespace op16 {
inline const AttrBinding attributes[] = {
    {"dbias_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::RMSNormBackwardAttributes*>(a)->dbias_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"dscale_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::RMSNormBackwardAttributes*>(a)->dscale_tensor_uid()); return s; }},
    {"dx_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::RMSNormBackwardAttributes*>(a)->dx_tensor_uid()); return s; }},
    {"dy_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::RMSNormBackwardAttributes*>(a)->dy_tensor_uid()); return s; }},
    {"inv_rms_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::RMSNormBackwardAttributes*>(a)->inv_rms_tensor_uid()); return s; }},
    {"scale_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::RMSNormBackwardAttributes*>(a)->scale_tensor_uid()); return s; }},
    {"x_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::RMSNormBackwardAttributes*>(a)->x_tensor_uid()); return s; }},
};
} // namespace op16

namespace op17 {
inline const AttrBinding attributes[] = {
    {"in_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ReductionAttributes*>(a)->in_tensor_uid()); return s; }},
    {"is_deterministic", false, AttrType::Bool, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Bool; s.present = true; s.b = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ReductionAttributes*>(a)->is_deterministic(); return s; }},
    {"mode", false, AttrType::Dtype, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Dtype; s.present = true; s.dtype = ::hipdnn_flatbuffers_sdk::data_objects::EnumNameReductionMode(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ReductionAttributes*>(a)->mode()); return s; }},
    {"out_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ReductionAttributes*>(a)->out_tensor_uid()); return s; }},
};
} // namespace op17

namespace op18 {
inline const AttrBinding attributes[] = {
    {"generate_index", true, AttrType::Bool, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Bool; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ResampleFwdAttributes*>(a)->generate_index(); s.present = v.has_value(); if(v) s.b = *v; return s; }},
    {"index_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ResampleFwdAttributes*>(a)->index_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"padding_mode", false, AttrType::Dtype, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Dtype; s.present = true; s.dtype = ::hipdnn_flatbuffers_sdk::data_objects::EnumNamePaddingMode(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ResampleFwdAttributes*>(a)->padding_mode()); return s; }},
    {"resample_mode", false, AttrType::Dtype, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Dtype; s.present = true; s.dtype = ::hipdnn_flatbuffers_sdk::data_objects::EnumNameResampleMode(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ResampleFwdAttributes*>(a)->resample_mode()); return s; }},
    {"x_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ResampleFwdAttributes*>(a)->x_tensor_uid()); return s; }},
    {"y_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::ResampleFwdAttributes*>(a)->y_tensor_uid()); return s; }},
};
} // namespace op18

namespace op19 {
inline const AttrBinding attributes[] = {
    {"dbias_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormBackwardAttributes*>(a)->dbias_tensor_uid()); return s; }},
    {"dscale_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormBackwardAttributes*>(a)->dscale_tensor_uid()); return s; }},
    {"dx_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormBackwardAttributes*>(a)->dx_tensor_uid()); return s; }},
    {"dy_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormBackwardAttributes*>(a)->dy_tensor_uid()); return s; }},
    {"epsilon_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormBackwardAttributes*>(a)->epsilon_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"inv_variance_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormBackwardAttributes*>(a)->inv_variance_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"mean_tensor_uid", true, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; auto v = static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormBackwardAttributes*>(a)->mean_tensor_uid(); s.present = v.has_value(); if(v) s.i = static_cast<std::int64_t>(*v); return s; }},
    {"normalized_dim_count", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormBackwardAttributes*>(a)->normalized_dim_count()); return s; }},
    {"scale_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormBackwardAttributes*>(a)->scale_tensor_uid()); return s; }},
    {"x_tensor_uid", false, AttrType::Int, +[](const void* a) -> ScalarValue { ScalarValue s; s.type = AttrType::Int; s.present = true; s.i = static_cast<std::int64_t>(static_cast<const ::hipdnn_flatbuffers_sdk::data_objects::LayernormBackwardAttributes*>(a)->x_tensor_uid()); return s; }},
};
} // namespace op19

inline const OpSchemaEntry entries[] = {
    {"BatchnormInferenceAttributes", "BatchnormInferenceAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::BatchnormInferenceAttributes), nullptr, 0u, nullptr, 0u, op0::attributes, 6u},
    {"PointwiseAttributes", "PointwiseAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::PointwiseAttributes), nullptr, 0u, nullptr, 0u, op1::attributes, 12u},
    {"BatchnormBackwardAttributes", "BatchnormBackwardAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::BatchnormBackwardAttributes), nullptr, 0u, nullptr, 0u, op2::attributes, 8u},
    {"BatchnormAttributes", "BatchnormAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::BatchnormAttributes), nullptr, 0u, nullptr, 0u, op3::attributes, 12u},
    {"ConvolutionFwdAttributes", "ConvolutionFwdAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::ConvolutionFwdAttributes), nullptr, 0u, nullptr, 0u, op4::attributes, 4u},
    {"ConvolutionBwdAttributes", "ConvolutionBwdAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::ConvolutionBwdAttributes), nullptr, 0u, nullptr, 0u, op5::attributes, 4u},
    {"ConvolutionWrwAttributes", "ConvolutionWrwAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::ConvolutionWrwAttributes), nullptr, 0u, nullptr, 0u, op6::attributes, 4u},
    {"BatchnormInferenceAttributesVarianceExt", "BatchnormInferenceAttributesVarianceExt", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::BatchnormInferenceAttributesVarianceExt), nullptr, 0u, nullptr, 0u, op7::attributes, 7u},
    {"MatmulAttributes", "MatmulAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::MatmulAttributes), nullptr, 0u, nullptr, 0u, op8::attributes, 3u},
    {"RMSNormAttributes", "RMSNormAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::RMSNormAttributes), nullptr, 0u, nullptr, 0u, op9::attributes, 7u},
    {"LayernormAttributes", "LayernormAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::LayernormAttributes), nullptr, 0u, nullptr, 0u, op10::attributes, 9u},
    {"sdpa_fwd", "SdpaAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::SdpaAttributes), op11::operands, 21u, op11::results, 7u, op11::attributes, 13u},
    {"BlockScaleDequantizeAttributes", "BlockScaleDequantizeAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::BlockScaleDequantizeAttributes), nullptr, 0u, nullptr, 0u, op12::attributes, 4u},
    {"BlockScaleQuantizeAttributes", "BlockScaleQuantizeAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::BlockScaleQuantizeAttributes), nullptr, 0u, nullptr, 0u, op13::attributes, 6u},
    {"SdpaBackwardAttributes", "SdpaBackwardAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::SdpaBackwardAttributes), nullptr, 0u, nullptr, 0u, op14::attributes, 28u},
    {"CustomOpAttributes", "CustomOpAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::CustomOpAttributes), nullptr, 0u, nullptr, 0u, nullptr, 0u},
    {"RMSNormBackwardAttributes", "RMSNormBackwardAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::RMSNormBackwardAttributes), nullptr, 0u, nullptr, 0u, op16::attributes, 7u},
    {"ReductionAttributes", "ReductionAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::ReductionAttributes), nullptr, 0u, nullptr, 0u, op17::attributes, 4u},
    {"ResampleFwdAttributes", "ResampleFwdAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::ResampleFwdAttributes), nullptr, 0u, nullptr, 0u, op18::attributes, 6u},
    {"LayernormBackwardAttributes", "LayernormBackwardAttributes", static_cast<int>(::hipdnn_flatbuffers_sdk::data_objects::NodeAttributes::LayernormBackwardAttributes), nullptr, 0u, nullptr, 0u, op19::attributes, 10u},
};

} // namespace generated

inline const OpSchemaEntry* opSchemaEntries(std::size_t& count)
{
    count = sizeof(generated::entries) / sizeof(generated::entries[0]);
    return generated::entries;
}

inline const OpSchemaEntry* lookupOpByName(std::string_view opcode)
{
    for(const auto& e : generated::entries)
        if(e.opcode == opcode)
            return &e;
    return nullptr;
}

inline const OpSchemaEntry* lookupOpByType(int attributesType)
{
    for(const auto& e : generated::entries)
        if(e.attributesType == attributesType)
            return &e;
    return nullptr;
}

} // namespace hipdnn_flatbuffers_sdk::umd
