import copy
import importlib

import pytest

pytestmark = pytest.mark.unit

Solution = importlib.import_module("Tensile.SolutionStructs.Solution").Solution
_fn = Solution.setGlobalLoadTileDimClassic

def _strict_eq(a, b):
    if type(a) is not type(b):
        return False
    if isinstance(a, dict):
        if set(a.keys()) != set(b.keys()):
            return False
        return all(_strict_eq(a[k], b[k]) for k in a)
    if isinstance(a, (list, tuple)):
        return len(a) == len(b) and all(_strict_eq(x, y) for x, y in zip(a, b))
    return a == b

CASES = [{'name': 'other_tlu',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': 2,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 4,
            'UseGeneralizedNLCOneA': False,
            'MacroTileA': 127},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 8,
  'tep': 8,
  'depthU': 17,
  'prr': True,
  'rv': True,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 2,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 4,
          'UseGeneralizedNLCOneA': False,
          'MacroTileA': 127,
          'NumLoadsPerpendicularA': 2,
          'NumTotalPackedLoadsA': -1,
          'LSCA': 63,
          'LSPA': 9},
  'stdout': ''},
 {'name': 'other_nottlu',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': 2,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': False},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 4,
            'UseGeneralizedNLCOneA': False,
            'MacroTileA': 127},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 8,
  'tep': 8,
  'depthU': 17,
  'prr': True,
  'rv': True,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 2,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': False},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 4,
          'UseGeneralizedNLCOneA': False,
          'MacroTileA': 127,
          'NumLoadsPerpendicularA': 2,
          'NumTotalPackedLoadsA': -1,
          'LSCA': 9,
          'LSPA': 63},
  'stdout': ''},
 {'name': 'other_rej_gt',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': 8,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 4,
            'UseGeneralizedNLCOneA': False,
            'MacroTileA': 128},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 8,
  'tep': 8,
  'depthU': 16,
  'prr': True,
  'rv': False,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 8,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 4,
          'UseGeneralizedNLCOneA': False,
          'MacroTileA': 128,
          'Valid': False},
  'stdout': '\nreject: A nlc > numLoads\n'},
 {'name': 'other_eq',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': 4,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 4,
            'UseGeneralizedNLCOneA': False,
            'MacroTileA': 127},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 4,
  'tep': 4,
  'depthU': 17,
  'prr': True,
  'rv': True,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 4,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 4,
          'UseGeneralizedNLCOneA': False,
          'MacroTileA': 127,
          'NumLoadsPerpendicularA': 1,
          'NumTotalPackedLoadsA': -1,
          'LSCA': 31,
          'LSPA': 17},
  'stdout': ''},
 {'name': 'other_rej_mod',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': 3,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 4,
            'UseGeneralizedNLCOneA': False,
            'MacroTileA': 128},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 12,
  'tep': 8,
  'depthU': 16,
  'prr': True,
  'rv': False,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 3,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 4,
          'UseGeneralizedNLCOneA': False,
          'MacroTileA': 128,
          'NumLoadsPerpendicularA': 1,
          'Valid': False},
  'stdout': '\nreject: A: numLoads 4 % numLoadsCoalesced 3 != 0\n'},
 {'name': 'other_rej_tvc',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': 2,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 4,
            'UseGeneralizedNLCOneA': False,
            'MacroTileA': 128},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 7,
  'tep': 8,
  'depthU': 16,
  'prr': True,
  'rv': False,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 2,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 4,
          'UseGeneralizedNLCOneA': False,
          'MacroTileA': 128,
          'NumLoadsPerpendicularA': 2,
          'Valid': False},
  'stdout': '\nreject: A: totalVectorsCoalesced 7 % numLoadsPara 2 != 0\n'},
 {'name': 'other_rej_tep',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': 2,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 4,
            'UseGeneralizedNLCOneA': False,
            'MacroTileA': 128},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 8,
  'tep': 7,
  'depthU': 16,
  'prr': True,
  'rv': False,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 2,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 4,
          'UseGeneralizedNLCOneA': False,
          'MacroTileA': 128,
          'NumLoadsPerpendicularA': 2,
          'Valid': False},
  'stdout': '\nreject: A: totalElementsPerp 7 % numLoadsPerp 2 != 0\n'},
 {'name': 'nlc1',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': 1,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 4,
            'UseGeneralizedNLCOneA': False,
            'MacroTileA': 127},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 8,
  'tep': 8,
  'depthU': 17,
  'prr': True,
  'rv': True,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 1,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 4,
          'UseGeneralizedNLCOneA': False,
          'MacroTileA': 127,
          'NumLoadsPerpendicularA': 4,
          'NumTotalPackedLoadsA': -1,
          'LSCA': 127,
          'LSPA': 5},
  'stdout': ''},
 {'name': 'nlc1_rej',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': 1,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 3,
            'UseGeneralizedNLCOneA': False,
            'MacroTileA': 128},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 1,
  'tep': 1,
  'depthU': 16,
  'prr': True,
  'rv': False,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 1,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 3,
          'UseGeneralizedNLCOneA': False,
          'MacroTileA': 128,
          'Valid': False},
  'stdout': '\nreject: A: No NumLoadsCoalesced=1 found\n'},
 {'name': 'nlcm1',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': -1,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 4,
            'UseGeneralizedNLCOneA': False,
            'MacroTileA': 127},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 8,
  'tep': 8,
  'depthU': 17,
  'prr': True,
  'rv': True,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 4,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 4,
          'UseGeneralizedNLCOneA': False,
          'MacroTileA': 127,
          'NumLoadsPerpendicularA': 1,
          'NumTotalPackedLoadsA': -1,
          'LSCA': 31,
          'LSPA': 17},
  'stdout': ''},
 {'name': 'nlcm1_rej',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': -1,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 3,
            'UseGeneralizedNLCOneA': False,
            'MacroTileA': 128},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 1,
  'tep': 1,
  'depthU': 16,
  'prr': True,
  'rv': False,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': -1,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 3,
          'UseGeneralizedNLCOneA': False,
          'MacroTileA': 128,
          'Valid': False},
  'stdout': '\nreject: A: No NumLoadsCoalesced=-1 found\n'},
 {'name': 'nlcm1_only1',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': -1,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 4,
            'UseGeneralizedNLCOneA': False,
            'MacroTileA': 127},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 1,
  'tep': 4,
  'depthU': 17,
  'prr': True,
  'rv': True,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 1,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 4,
          'UseGeneralizedNLCOneA': False,
          'MacroTileA': 127,
          'NumLoadsPerpendicularA': 4,
          'NumTotalPackedLoadsA': -1,
          'LSCA': 127,
          'LSPA': 5},
  'stdout': ''},
 {'name': 'egltr',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 1,
            'NumLoadsCoalescedA': 3,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 6,
            'UseGeneralizedNLCOneA': False,
            'MacroTileA': 127},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 2,
  'tep': 3,
  'depthU': 17,
  'prr': True,
  'rv': True,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 1,
          'NumLoadsCoalescedA': 2,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 6,
          'UseGeneralizedNLCOneA': False,
          'MacroTileA': 127,
          'NumLoadsPerpendicularA': 3,
          'NumTotalPackedLoadsA': -1,
          'LSCA': 63,
          'LSPA': 6},
  'stdout': ''},
 {'name': 'wsgr1',
  'state': {'WaveSeparateGlobalReadA': 1,
            'NumThreads': 100,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': 1,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 4,
            'UseGeneralizedNLCOneA': False,
            'MacroTileA': 128},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 8,
  'tep': 8,
  'depthU': 16,
  'prr': True,
  'rv': True,
  'out': {'WaveSeparateGlobalReadA': 1,
          'NumThreads': 100,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 1,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 4,
          'UseGeneralizedNLCOneA': False,
          'MacroTileA': 128,
          'NumLoadsPerpendicularA': 4,
          'NumTotalPackedLoadsA': -1,
          'LSCA': 128,
          'LSPA': 4},
  'stdout': ''},
 {'name': 'wsgr2',
  'state': {'WaveSeparateGlobalReadA': 2,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': 2,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 4,
            'UseGeneralizedNLCOneA': False,
            'MacroTileA': 127},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 8,
  'tep': 8,
  'depthU': 17,
  'prr': True,
  'rv': True,
  'out': {'WaveSeparateGlobalReadA': 2,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 2,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 4,
          'UseGeneralizedNLCOneA': False,
          'MacroTileA': 127,
          'NumLoadsPerpendicularA': 2,
          'NumTotalPackedLoadsA': -1,
          'LSCA': 63,
          'LSPA': 4},
  'stdout': ''},
 {'name': 'dtv_tlu',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': 1,
            'DirectToVgprA': 1,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 6,
            'GlobalReadVectorWidthA': 2,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 6,
            'UseGeneralizedNLCOneA': False,
            'MacroTileA': 127},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 6,
  'tep': 6,
  'depthU': 17,
  'prr': True,
  'rv': True,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 3,
          'DirectToVgprA': 1,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 6,
          'GlobalReadVectorWidthA': 2,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 6,
          'UseGeneralizedNLCOneA': False,
          'MacroTileA': 127,
          'NumLoadsPerpendicularA': 2,
          'NumTotalPackedLoadsA': -1,
          'LSCA': 42,
          'LSPA': 9},
  'stdout': ''},
 {'name': 'dtv_else',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': 1,
            'DirectToVgprA': 1,
            'ProblemType': {'TLUA': False},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 2,
            'MatrixInstK': 1,
            'LocalSplitU': 5,
            'MIInputPerThread': 4,
            'NumLoadsA': 6,
            'UseGeneralizedNLCOneA': False,
            'MacroTileA': 127},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 6,
  'tep': 6,
  'depthU': 5,
  'prr': True,
  'rv': True,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 3,
          'DirectToVgprA': 1,
          'ProblemType': {'TLUA': False},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 2,
          'MatrixInstK': 1,
          'LocalSplitU': 5,
          'MIInputPerThread': 4,
          'NumLoadsA': 6,
          'UseGeneralizedNLCOneA': False,
          'MacroTileA': 127,
          'NumLoadsPerpendicularA': 2,
          'NumTotalPackedLoadsA': -1,
          'LSCA': 2,
          'LSPA': 63},
  'stdout': ''},
 {'name': 'gnlc_ok',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': 2,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 4,
            'UseGeneralizedNLCOneA': True,
            'MacroTileA': 128},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 8,
  'tep': 8,
  'depthU': 16,
  'prr': True,
  'rv': True,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 1,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 4,
          'UseGeneralizedNLCOneA': True,
          'MacroTileA': 128,
          'NumLoadsPerpendicularA': 2,
          'NumTotalPackedLoadsA': 2,
          'LSCA': 128,
          'LSPA': 8},
  'stdout': ''},
 {'name': 'gnlc_rej',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': 2,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 4,
            'UseGeneralizedNLCOneA': True,
            'MacroTileA': 128},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 8,
  'tep': 8,
  'depthU': 12,
  'prr': True,
  'rv': True,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 1,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 4,
          'UseGeneralizedNLCOneA': True,
          'MacroTileA': 128,
          'NumLoadsPerpendicularA': 1,
          'Valid': False,
          'NumTotalPackedLoadsA': 1,
          'LSCA': 128,
          'LSPA': 12},
  'stdout': '\nreject: GNLCA: totalLoadsNeeded (6) % numWaves (4) != 0\n'},
 {'name': 'gnlc_nw',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 100,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': 2,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 4,
            'UseGeneralizedNLCOneA': True,
            'MacroTileA': 128},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 8,
  'tep': 8,
  'depthU': 16,
  'prr': True,
  'rv': True,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 100,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 1,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 4,
          'UseGeneralizedNLCOneA': True,
          'MacroTileA': 128,
          'NumLoadsPerpendicularA': 8,
          'NumTotalPackedLoadsA': 8,
          'LSCA': 128,
          'LSPA': 2},
  'stdout': ''},
 {'name': 'gnlc_tln',
  'state': {'WaveSeparateGlobalReadA': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrA': 0,
            'NumLoadsCoalescedA': 2,
            'DirectToVgprA': 0,
            'ProblemType': {'TLUA': True},
            'MIWaveTileA': 1,
            'GlobalReadVectorWidthA': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsA': 4,
            'UseGeneralizedNLCOneA': True,
            'MacroTileA': 128},
  'tc': 'A',
  'numLoads': 0,
  'tvc': 8,
  'tep': 8,
  'depthU': 17,
  'prr': True,
  'rv': True,
  'out': {'WaveSeparateGlobalReadA': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrA': 0,
          'NumLoadsCoalescedA': 1,
          'DirectToVgprA': 0,
          'ProblemType': {'TLUA': True},
          'MIWaveTileA': 1,
          'GlobalReadVectorWidthA': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsA': 4,
          'UseGeneralizedNLCOneA': True,
          'MacroTileA': 128,
          'NumLoadsPerpendicularA': 2,
          'NumTotalPackedLoadsA': 2,
          'LSCA': 128,
          'LSPA': 9},
  'stdout': ''},
 {'name': 'other_B',
  'state': {'WaveSeparateGlobalReadB': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrB': 0,
            'NumLoadsCoalescedB': 2,
            'DirectToVgprB': 0,
            'ProblemType': {'TLUB': True},
            'MIWaveTileB': 1,
            'GlobalReadVectorWidthB': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsB': 4,
            'UseGeneralizedNLCOneB': False,
            'MacroTileB': 127},
  'tc': 'B',
  'numLoads': 0,
  'tvc': 8,
  'tep': 8,
  'depthU': 17,
  'prr': True,
  'rv': True,
  'out': {'WaveSeparateGlobalReadB': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrB': 0,
          'NumLoadsCoalescedB': 2,
          'DirectToVgprB': 0,
          'ProblemType': {'TLUB': True},
          'MIWaveTileB': 1,
          'GlobalReadVectorWidthB': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsB': 4,
          'UseGeneralizedNLCOneB': False,
          'MacroTileB': 127,
          'NumLoadsPerpendicularB': 2,
          'NumTotalPackedLoadsB': -1,
          'LSCB': 63,
          'LSPB': 9},
  'stdout': ''},
 {'name': 'egltr_B',
  'state': {'WaveSeparateGlobalReadB': 0,
            'NumThreads': 256,
            'WavefrontSize': 64,
            'enableGLTrB': 1,
            'NumLoadsCoalescedB': 3,
            'DirectToVgprB': 0,
            'ProblemType': {'TLUB': True},
            'MIWaveTileB': 1,
            'GlobalReadVectorWidthB': 4,
            'MatrixInstK': 1,
            'LocalSplitU': 1,
            'MIInputPerThread': 1,
            'NumLoadsB': 6,
            'UseGeneralizedNLCOneB': False,
            'MacroTileB': 127},
  'tc': 'B',
  'numLoads': 0,
  'tvc': 2,
  'tep': 3,
  'depthU': 17,
  'prr': True,
  'rv': True,
  'out': {'WaveSeparateGlobalReadB': 0,
          'NumThreads': 256,
          'WavefrontSize': 64,
          'enableGLTrB': 1,
          'NumLoadsCoalescedB': 2,
          'DirectToVgprB': 0,
          'ProblemType': {'TLUB': True},
          'MIWaveTileB': 1,
          'GlobalReadVectorWidthB': 4,
          'MatrixInstK': 1,
          'LocalSplitU': 1,
          'MIInputPerThread': 1,
          'NumLoadsB': 6,
          'UseGeneralizedNLCOneB': False,
          'MacroTileB': 127,
          'NumLoadsPerpendicularB': 3,
          'NumTotalPackedLoadsB': -1,
          'LSCB': 63,
          'LSPB': 6},
  'stdout': ''}]

@pytest.mark.parametrize("case", CASES, ids=[c["name"] for c in CASES])
def test_setGlobalLoadTileDimClassic_kills(case, capsys):
    state = copy.deepcopy(case["state"])
    rv = _fn(
        state,
        case["tc"],
        case["numLoads"],
        case["tvc"],
        case["tep"],
        case["depthU"],
        case["prr"],
    )
    captured = capsys.readouterr()
    assert _strict_eq(rv, case["rv"]), (rv, case["rv"])
    assert _strict_eq(state, case["out"]), (state, case["out"])
    assert captured.out == case["stdout"]
